// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9jXLcNpYw+irY3q2yPdtq2U5mKqOq1Kwi2YnWf7qSnLm7ke8ETaK7MWKDHACU3Em5",
	"6r7DfcP7JF/hHIAESfCn5ZYc29ytmlhN/B7gHJz/8/skStdZKpjQanLw+0RFK7am8M/DuUqTXLNTqlfm",
	"75ipSPJM81RMDiZnLJNMmW6ECkJtW7LgCSMZ1avZZDrJZJoxqTmD8bLgOBcrVvY2TYhOCcVxUkH0ihG1",
	"UZqtZ+R1qhnRK6oJFRvC3nOluVhi0xueJGTOSHrN5I3kWjNhVsDe03WWsMnBZP+ayv0kXe7TLJsl6XIy",
	"nehNZr4oLblYTj58KH5J5/9kkZ58mE4Os+wCfgst27Qm6QLWSLMs4RE1X2Feka8nB78gcBWbvKvPNp28",
	"3zON9q6pFHRtIPSLm+3IdcIFuHGPUqGZ0GYtNEneLCYHv/w++Q/JFpODyb/vl8e4b89w/zlPmOv0Ydrd",
	"9owlVPNrPGzTWLJ/5Vyy2KwLTu5dAzy19T0T1z9TiUddOXhWfqBxzE1bmpxWmtSOYlqD9jNxzWUq1kxo",
	"ck0lp/OEkSu22bumSW6uDZdqSrgw62IxiXMzDJG50HzNZsQc1hXbECpigj0YjVZknStt7syc6RvGBHkC",
	"DZ7++RsSraikkWZSzSaNbbfcEweGU5le85jJ84xFw88qAEdzClVA0vI29owFzT5MJ+ZqteBcOSExrQpo",
	"PPn//9//rwoDkqRiOSVKU6nJDdcrQknCtGaSpJKIfD1ncgqwi1KhKRdEpORmxTVTGY3YbBCq/T5JBRsA",
	"qJM1XbI2cPfd8hORcNHe+92Hd91ne66pzlWYIuA3Qw8oUVwskyqMLS2L2TVHkDgScSpZRi1NODcgxn+e",
	"5ULgv55JmcrJdPJWXIn0RkymE0MgEqZZPJyuVHfgz9n46C2i8a1cVeOTW2bjQ7nuxidvI1VA/5wmOd7c",
	"En2q4D5mCy6YIhRub0yuoQfJFYvJfANvUpUkV1EpjBhvBf9XzhAfLGH3xzV3n4sQvW/eb59+wmTvPvLO",
	"I0gaFzYEtzoJqm4dd6Sau3/JlYb7611b29jskWu2VgNoT+0MS1ynUtJNL/3Ebng/urFsJ0f+unHWgfM0",
	"x7lgkomIhTgh+8lwLojjWZJuWEzeHJ3sGRglnApNuDlFQzENei1opMmcRlfmoeqcO3SX/PX0kCx1nq/X",
	"VG4Gkq4k8YGo2snWT4wmerWZTCfHbClpzOIAqdqaPFVXW87R2sSbvLVNgDJVGxTLNaDL9eooFQu+bMLJ",
	"fDNv3IIvm9eL5noVBi90M3AI3izT7+3Zy5Zub89e9t+JYupytNCt+IHqKMCBw8+EAx/PEgZMFhdkDj8r",
	"9q/cXLPmfhO+5jrMW6zpe77O15Y1MFc+YzJiQgMCLOxtUgZf8iymmhFLVWFOM9UwunhajArEdM2FmXZy",
	"8KTYPBeaLZlEXlWxhEU6lX007CWds+TcNTYd8yhiSl2sJFOrNIn7BvDX9aHtIM4tZFsOxH0msX3oDHwS",
	"S6EBTgjAOSPsPYtyw/dy0XFeqnW+w+q4OCOw6cPpPt6tD1NzCCfY4Umd8E/N/aWaLTd9o52lSZLm+tw1",
	"r1/4YpzQNT8ye14YRGfnfGnYlTOzdRW4rK1NifTEWyLtjwtDvIniS8FiEpV9yUKmazigo8MAYcj4z0wq",
	"mLEB+tMT+61yztf4G4sJQgQfKK7KZVmmcmGQFrc+I+dMmo5ErdI8AWb8mkmzlShdCv5bMZpyD1VCtdmW",
	"QRIpaIKyEXLya7ohkplxSS68EaCJmpFXqTRYu0gPyErrTB3s7y+5nl19p2Y8NUe6zgXXm30jEUg+z3Uq",
	"1X7Mrlmyr/hyj8rIyAeRziXbpxnfg8UKvHPr+N8lU2kuI6aCJPOKi7gJyxdcxEDGCLa0ol4BMvfSnj07",
	"vyBuAgQrQtA79BKYBhBcLJjElsVJMxFnKRca/ogSbqimyudrrpW7LwbOM3JEhUhBskJaF8/IiSBHdM2S",
	"I6rYnYPSQE/tGZCFgblmmsZU0z6cfAMwesU0BUy2rGVXj1bssrLaRBVM3u2Gwe6N17DEN3tVvE3alW9F",
	"NwxfvAXtADYa7qEjq61NR2Jx98SieL7Cwk7n2Qx6+trfmw/NF3AkXZ+AdJmzRsK1HanA49+KVjiRu3q+",
	"f5c0y5iR/NJcxIQamVXuRZIZoJKj87MpWacxS1hsBK6rfM6kYJopwlMAJs34zOM31Oz6yaxzCU3Cwt5n",
	"XKLqhUWpiFVIkIX+qEAtaMY1TXjM9Qa4H7gx5cRmmkUq11Qjr/3N00mT9Z5O2HstaZf6t8CzxhHX8aem",
	"FzYDE6rxcjHlBHkDXrQUOBgDc2bgnKVZnsBP8w38enh6QhRgjIE9tDc7N3SNr9e5pvOEBbTAeJGCXOUF",
	"SDKK/eXbPSaiNGYxOX32qvz3i6Pzf3/y2CxnRl45Tn7FiHmZZgWvyVkCHD3170MXw4pUoXIk841mIcQB",
	"Fla+DipETkSMlwzWJIs7gX2Q4AOp+ldOE77gLAZ9WRBBcx4gdm9Pju/hnLxFKLoMqbvewu8AdbMNoL4M",
	"3oQrtiHYy9u/FVG5UnmV+688FL0X2Gy5XxN1D4CpkUJ3myuXYzvS16KyKy8UzTKZXtNkP2aC02R/QXmS",
	"S0ZUoX8qdulZE1QL3AlflIZA1aR4XtMwjtohm/LctAQcSY0MXsB8EHYZ8oric4BrLL6hns2cbOpj2oy8",
	"EOmNIJHXUDJyCKBj8ZQcM8HNfw2EnlOe4KKGcSpuzKBS1r8N3haCd6AYqH2D5fHFTFOeKHhAUsEINSin",
	"3XFHuZTAgWhzpo53NZf6zCNpNd0TVfpCUqFgpgveZuQy7Yjma4YzFUvTRV8WI19k1mWvoU4JFaleMVk5",
	"bcMA7ZmxwpyIMvSiuYqf8jUVRDIaw22y7QhHnDB8nYMOnae5tisulhckaOkc0D3+kQmG73R49zPHysyW",
	"RUskKlVo3FAFlM+8WTHJM5zWf9f/8m3wXZeMqqCgQh7OJWeLRwRblKyDm/OBGrTTgQKiG9UJhG6kgd3Q",
	"WFrDAI36VLuCaejKFQAoz78TWfptGhUYTeFSpgtyIY2g9Zwmik2J1VX7qnjzfTKdQIOtle+11dmxar+6",
	"oWs/+3rzKjSb99H6SpS3jvuShLcbR+lQYe/+iVQPdmlInvkIOlk+T1j9D0c3TqlU0PR8IyL4x8+GlzUt",
	"UL94Ik5lupRMmQN+a0Qca4bNWOSavsoTzbOEvbkRTCpYyTWP2DEz0g1XRnYwnYYB+5mQaZKsmdD2zfR2",
	"2PquDmlTgKe1RQG3M5aliutUboJAM7Bq/dCArP+xgPLzhDHt4Ad/hOCNcPSgjj/4sMdfhp4AXsIFX9bN",
	"n8OMCT9yHeje51HwouDNz1kkmb6FO8ItZv1J6yzUDWCQ5e5UXqXCHHTTE6X6mq6xWb+jU6l5SInt1M9Y",
	"+qMHbeDdbknNneAuZSqevc/MXQqzITIVhBUNCL5m8BCZseM8AZ0KXzM1uxRmk7YFV+TXPxH7/78ekD3y",
	"igsjWx6QX//0K1lbee3x3p//OiN75Kc0l41PT78xn47pxgDtVSr0qtriyd43T0yL4KcnT73Of2fsqj76",
	"X2aX4jzPslQaIcAcJNWpWcSeaXhQiJSGN0Y90kM2W86mMAwXZGWWXIzHrpncwG+PzLy/7v16QM6oWJa9",
	"Hu999ysA7slTcvjKnP135PAVtp7+ekBAk+YaP5k+eWpbKw086pOnekXWAEPss//rATnXLCuXte/64GL8",
	"HvsX2dr0OkePmup+vivBYl7O77yJLsUzdP0z0COP976bPvnL3tNv7LEGmY2jXOl0jcTlRCzSLoVFnd8B",
	"fQ4qZWMSwUDEIpk9hOCUdYHUG4QLvJAgygFrWLXDN9gMXHhzcfh71aCVrTaKRzTxxhvV0KPNarRZ7ZdM",
	"yHD5w/a5hTXqXSseN1zlmn5cYS1STeD0Xdm6fdZAmok3YQ7AeXIsnFRvrtnNikcr0E5ATzLINc5MA56k",
	"ATr6upjFtSFO1i1EyPDonlA67MzCTp0fpu3ecaWUZpsUjmeAZLV13c5Zri7AtmhnCh8wc14eQIvND7pX",
	"VR+o0KumsIG7Pytwx6p5CAZcxKrXlNuntPOa+q8dKkQc5QM1ge+RuBOVQbeDXNPdpAeqyIu3AfLI03CV",
	"cj7Cq9WdTDIRM8ni1mf4zDZwD2/ruH163+o8nZtUadLKYdjPPqNh1Rnwc5QKwSIr+ReHHXJTAob95DhM",
	"iOxncnLsK5VqM4QvBvZ85T0dtfte8HrFLI5QO9Jm1m0NBN9XQg8iKuC1VKjPBfcpmvDfUPFYBIowueaC",
	"JtNizejAZbpNCdNR23HR+I1INpMDLXNWu5q1XU09ALYfpS87NwHhBrN8J3VXKq5K3IXGunGGmsol08Oe",
	"TX8pF9AvrI7DIYdtyRunScYLcw8iizIzNLa2ZnqVxlWU8pVUbwUDVQ4opCKdys0ZU5X1damBulbsjdzV",
	"rDprAYUT8w5KrjdHKxZdtRGk9rZ17K2SLO56kMh0IRmTBiPQan3LN2Av+AaUEk99TlzRR5D+9s3fjva3",
	"jtSj590CmOWtc5EUr1N9iuc0mU5OmYjxrhVKvlOq1ODwkPZ9lBO2t6kspb1Zucj2NsXyO4axG2uCv1W7",
	"bpmYtqvcwPGsJunDLLGRTvTm9pcLXJG2ZYVKNAA2qFx0DxNkWv/MJFjnA+8oXxuOcZ25vdcGv4aeJS87",
	"zAR2K+yzEUd4RI4F19l6eOBcJ8R/D5uEQ0D5+4rpFUOO4uL0lRHKrWF4viGUAB6AlkHLHPwB0NXXgmGe",
	"pgmjYFe9ZiJGH/Ma1E9fkTUV+YKC2CvbvCY+BOIsb02TmvAdTJVa3z6Lgh61KcnEW6GcZvJ2xKeC5S3b",
	"aSMTPTTLffZWWADsJV+waBMl7Kc0vXJwchv+gS1S6VsqDheaSe9vbHDG5mnqtyh/2AYUlaU0pg60qa+m",
	"dRh/gW3jeGtuAudWAk7ieu+ULagPviu+oLbX27EEoUHa8M4PIg9BrPn2oxHRIkDVBlb9ZUscrK26jke1",
	"z5VVBL6HltbTrIaRIde68lvVwxp/V6Mi+5P7U3snMUgHZs0Wo6v0H81Vejqx6r9hJ+iYjN35WIes/8dM",
	"Q4qHY3SaairFUXnYb8rGdqBDirlptOaC6lSSLJdZqvACO9rbtZImiTXQpjpacbEE54cOZFmY78AIKnTM",
	"go41vmuob2kN7h4kGgsaCu4zptLkugPcVCGTDM3DEMc9uoaEKpKaxuShyJOE8AURKf7yyGzW/Giefafr",
	"CphM7+mA3d6DB5xJds3TXL3a5qDtGbu+ycZar+NbHjho/tMkb/e6+im9cSrSRcIjDa5+0m7MBwCa12E3",
	"oF1w/4J9HbOWZBOdV662tvYr90aFgyb8rwQ/ze0TjdpA8ua8UAK3ap7WQbfMi8ogGJmPpjI5LOQax+3c",
	"1G2Y5Tfng7fwc1Xt77YRfrPNl2O+bA1XiOFbfSx0tCBqRZ/++S8H9PFsNns0FDTVSTsABci24tnRiorl",
	"p6Hs9TUEUV6wmw4qJ9iNpWtI7wrqJtk6vWbxMOLmSEPHRK5JeDaRCjZkqnbEbT+pwtdvq4tdMJN9irYo",
	"y4dxGtV1OKVRzNXVx/Rfs3U6lNcJjVB3oM/ySTGoXd1Q0HbfcVXxxENgVy91mTbj71Ra4etIcs0jmtw6",
	"SUdooX4OkObXcvLQV29Boc9ukaFvvtux56/R8oDUng/a4fNU2oSHJcfJrPPlrdLj1Bw+G2971JKExC0E",
	"v99iDUF/09D0Kk1CjhAXXiIKGml+XZpgre1xW+nPWZaD8X5VNcLWNkUImBi4DsuJWMYKqFZAa2CWVsFB",
	"6+FqT8SGTg6HQc3HNQQFzIAYt5jE8SPEgLm0Kp53bs3X1zB2p1RrJoXqSgWCkkhmW1Y203ATQd9Mtw4j",
	"xwIzNcVkcamE/6a5EZ0XC/5+SjCPxoolyZ7Sm4SRZZLO3WSwfpidLikXSrsQoWRDkpTGDKeANa3p+5dM",
	"LPVqcvD0z3+ZTuwQk4PJ//PL472/0r3fDvf+9+Dycu8fs0v4v18uL9/92+Xl3uXlny4v//buPx/+17B2",
	"j/728PJy9gs2DH3+jxDf1Z/4CrUFp2nCo4GPz1uvB17XD63vSrcBuGnyDetalZdzyxJPYvuuKdiieIK+",
	"WZHOaVJGcn0srbVMsU9ySzXvFvSl6UwXwDHadAnaevSaS9XwWMDiDACO6PTm3KsMHIOBcjQkM94y/s9/",
	"bwYR7NLfCQyb1sZyK/Ofs1ieMyaGxPHZa4Fha0y4OFhL/4ZbLAs9+61MA1s+LEWfytOyLa+5tVqucSGR",
	"Sjv/9gEDlO0LchVvQ6niFsdYDzMqq6pi4iSMmD4Y/etXXGM4m3K9JdS8q+bfgHbe/PZekt5dXVEZ31DJ",
	"QL2PIRtcLO2TSSoK9917T9o1uPDWXfhPBkBzO1PZVtkJw/boNxBFFU5E6Js8T9MbJln8ZrG4pfBTWas3",
	"a+Obt5DA16poU/nUtNBWPld2EPgeEIwq2D4smuVN5rwg8XZ66TXY+yxVZeYBumRCzy7FMxqtIGlClErJ",
	"VJaKGMOoS5YYr6k1dUU0o3OecL2ZXYr+uBjcROWWR2mSYK7nwlTTymqYRbbaAM3rcriEvNLYJJyj0bO+",
	"tIzhtTCvOQZnWTg1onbKkc15h3xdf0hTTU6OtxkKw46GUPZGpJN5yhxRQmiHd/mmoFznjnINXF7dKOQD",
	"tIBCcxXT6vG105EGV9zj+JlBS9ASrqmgS4zEBzqJbwbkE4+SPDZfblZMuN+dhXfOSJzeCCuRGLpuEzoE",
	"fMhsu3OMPOzlN3AzRevi3b1t/w89YItvpavGNe3gyap5uVWG3+VzVdns7Z6r5hBb+HWUACucOrKL9JhC",
	"FpE3uX6zsP/2nHlu805VFulNEfjqzxrsXPMqqn5tPDe+4NTDJrkcsM6zHvTYkulcChYjwi0YGtfKhOpg",
	"juqUJsub3PbYDchrEbMFzRM9Ofi98RYdkrlk9MpgdOdO5hty6a/rctL0UCovl6rzmH+Axds1dS9cp5om",
	"Lbpq88kLHAvNNDDPiKV+fyToWMGiCzr1CAYA1TRwWevnX9twkBpxddUb5b91YP30D5YZIPiAW0UQvNw4",
	"ALzdXF1hzq5tCs/EXEKS501Recbpcq350Buzey8dJVKOuZI5zPpDHtu4mJo6rtaimvOZXbPE5mZPb1hs",
	"lmVbI5mUmFyDcLinmc2w0QTDUqZ59sOmXd2W0DlLDB8PzLuNRyDQDersOFN7Of8cllvRP3ka2Ie/HO79",
	"L9377fHeX9/9slf8+x/7s3d/evQ37+MA3Smoet8Kek25tWsGE49jBnCP6rgzIkXPAqldlRgEH2iTOxKI",
	"w9fDnulrec8XJBfNeYtz3Gr+IA+X++mfLGGbPDYUpH1xRW5Ht44ishaj83RKIluWAyvnFB1KxtflzAN3",
	"HkogoQy/tt7jzGCPHRt850FxlwuuZ6TMW1H8CPnNDsivClNAKMxOOSW/rvEHzOhgfljhD5C/Aq63d9X+",
	"dvDLk72/vru8jP/06G+Xl/Evar0K36tnIkoNUz8kPIzZtkjnILoPCAPVtOYN6nN1WUK5EWsxB+Tg1EA4",
	"1ant7P7+wQ7yYeplDyoLFNQrLbkWe1Yb2scZl2Oe2w51yhYYM/QiNVIbNWHbaNKRZd1mCjS3ERfQaUwY",
	"fXzHZBVfYbKKBkJtl7ei2X23CdVbsp2FBIbWpmUWybDGoCAUnj2MlCSrPUaZuqxqHflKb7yYMEedVlSR",
	"OWOCuAHCUWDAS31MybtDl4wWRwJ1apYlm7LIUEsmoMbh2X1udUKerDVInGg/6iYf3zNp34l71uiPPfvD",
	"Fm9I4E2otglO/NO/oapy8MMMja7HD23ZVapJWkzbAeKTN+rU31JACplueQS3cAkIAL44oFnwroUjfILN",
	"qsE+jSYjS/DJw36CZzLIKaHJOI6xQF9q2YQww9JPA8CHk6PzZtEQqU+j7QPlPPvBUSbgaKxaXKtDSfr9",
	"fOMKE6r670rgEa/6XQ3PGzadsKujrpTl//fsz4//SrJ8nvCoWn0qLcPWn4k4lQqLuL1gG/Lw2YtHU5fp",
	"HKVxG79eiUWvBLP7eQR2zcW47NNWlMS6zR5jw1Xh3rNighjc8h4WrkJsV3m/EmpBuDkJGqF+qFZluDh9",
	"9fQftgOh2hBmWmQoArC+TCOakEPvEwD15eGLR156gGcvWqDnVnPOl4KGjcddS1KuG5S1Ji8PXzRWOSVr",
	"GrPuRZzClXnBNr2zHz87cxfsihWmmg4ghKc0JxjfxUHYXJYuGwd5+PKYXZ8cDzkLf007Og6Y+xYnAkvZ",
	"zaG0AWRGXuXKhRMenfsD9DOWhkAOo94tZuOWhtuxlYO4vFKevJV04vlp9hWL8B+HZsWI2dZ1IJpVD9hH",
	"MFE7q+zQ1Ad2nK5t0iWxrdIbq1E2PA08V7aC+POEL1eaHBkeJ018Ku85cjZLrJqLHhVa761Um4c51Lb3",
	"NZo533NsXfjY3569dKfz9qR8vsArheQKve0z6djC/+uMmCsC7HzCxRVmNYb5HDPa4cFzW51tm+q2Bq9y",
	"glYYDLoSAMf+a+Gq5ZY1XCzTXF1W5dJghc1bXA0ces9Dyb1wlr8jaOgxWsdU03KZPpqDmh/Yf+qWbsYn",
	"C54g03Xx8jyM+LiYK7bpXMQLttlqckP9e+auI3sLVJpLHHTww0nCAMrg0jUatEhveejevsylSiXXrSAv",
	"2x66pu3Q99nrYmRSKcHWhsChwE0ULQ37CsQjjiVThTtV78bJQyclrlKlBV2zgyyVekAobgeAisUGT96I",
	"k4Fof1c9uVuFBcWrwJSHy0eqKflyCflKQZY2E6B5EWV2kAPmEN664O+RlWMctK9muAPyEEx/4ERmflCP",
	"vBnsV5rrdA2VsVwoVJg/HZVDu1YOxWXQdufDZUZ0Ad4QNnINmQjQ8jHMPlJU2x/VQjtXC7XUsDpEvCtT",
	"ctWUMPVEoQaOma03tUOLWHu1KbVKpTZyV7TigpXrtMcP9KeaQKJWlwrJkWfCd+5RR1h9z6t0c2Tr63n1",
	"dPDD2yLUpPpLo6FLp1H7xR+zGcba8nOtx9Hp20Zc9dHp23ok9tHp29fmNS4bvYJA9UZf/LneHX+tjXDM",
	"1VWjv/mx3tv8VuvrRdBVgyO8D42YCu9bPQ79mCvLXfhpAgPRFUeNVuYVZkI3vGbt701/2aJD4SnbVeSp",
	"VRKtHWRLrqHuLD0dNZTMLyfi2v52Yt+XC6qu+utCuZ9PBPU/+IWdzjWVmtXLPZXI4//6A9XR6sh6GNVr",
	"SB2Zm629/Q4qS1Vbmf8pWKnK/MjFsoGZlSpW9R9t61BqEGw46PU7x6Zeibp2p0qPUXqDleAQb6bE4pRP",
	"sQqUcvj2rt9+2K3Frz7OgWJ306JIHm5qahnEVo7Sy+1Skx+uwb3IOni6kohTQ8BzeM9iW5wwFQgRgNEM",
	"E2uUKV4wwD3LbKKATlTq1Ml3Jx3rwcItRq7n12pLitMTXdqSQieMoy1DBZqW4wQIRmtJs3rLcpQaolsC",
	"0OOgXGncHMu9uj2j2GYe7+mqM2ERZD8DzofpwIpxrYMPCgluObRhvbsv6G3GqF/F/tp1bQc9tKZb8GT7",
	"Ondc0w/vtkpqBDSnxQfBfar5HVyDRDA6G3xyZ4PiIIZ5GIA2Y/Qq+GK9CjzGKshQFatAURDQTGWpAIax",
	"KQTWlIyuc7/ia8t5enR3xbyhPT/niRM92vYMH9GWtuCh9NtRV39wYieavdfk4duL53vfgcJtXjVNepNA",
	"fBRPWi1hpp3zae83cHgu+sHIB7P99ko+5mtRu6clEKYlWSlP2AOFMS9TL8zBqiIh2sHliRT5mkkekZPj",
	"GTnG6AsgvJcTmab6chLGkjRmnVNnTFrZnpi2M/I/aQ7EAxeDYdZrg+oLuuYJp5KkkaaJM6sljELEwm9M",
	"pq5Q5uO/fPstHB9FF5qIr20HrO8T6vPt08ePDPXSOY/3FdNL8x/No6sNmdugDVJk0p+RkwUx1KmA2BSj",
	"rKubARQw+1Qk9gBmlheu5Zar1qyyCC1IgngHB9V2595kXsV1J3pFhZxrkz16iUeGBX9UhvbEZv/ns2Ls",
	"ys+OAX5nV7hdGKBPRnpZLx/n+hofziH7KzulYHP9vRksV1CFlrA54PQCuG0Dhb3AEetiFI854Mf4kDE+",
	"pC4sbRcTgl12GwcCY4YlreJTVdLCdNojJn9ySas8iEGSFtLsUdL6UiWtDu3L/eTrDik0Qxp5rk7Waxbz",
	"oDuf7W8uHdVsuSmUyW6WOablhxzmbpTQLJqtM4P4ndmlfAHxotqhFBOtf5iNA98iy359CdWtDzjDoANn",
	"s812vps2m0sZ2V4TPNH5ESxBYaDBCbg4+jL965y5iHkW14DVGShfPoThrXbEF8BWemMK7FaH5XE9qzQG",
	"t6GEOdeaToSmc5acu8beBWzBMPu1ViShmYKllvTjXoqr1zMvhZmHeg4Vt9/Wi915o299lQfnu4XWU8JA",
	"IKVJsiG8zHzjocaKXjMQmMH7DBLZgVxPBV2yiu8XF4SSm1WbAmc7B+PixD8+XWzcSPi0TY2gqcOYQRxF",
	"lVpt6dH8IxNG+j9jWVrIxsFglgVNFGuUMrbvV7dBA4d21qNctqREepilYKTeQFUIzR5B/jy0rg8rO2KG",
	"tm2Ce+U6kN298TQvuT4z2wmtUTr/KvTK/JHral5zgm6D22TZcbl1XCUavnQUqHQuCDI6JXT6n9ZyqIJT",
	"DI6JdPyMXfP2J1var2bRuWIlC9m53kZh9WLxjVmnbfmCpljbf4CmuZL8v381MOzUnXxoYigBGTndVqk+",
	"qiX3W3TmscYiVrkC7nnNdCC5zJwR9p5FucYYrkGUyKytkxppvmaWmnxmmW/IA/WgmvjmwfpBNfGNESIf",
	"rB58fPKbD6EkW8Ns3eXtOMvF5MM7UNFVfwxko7n+mcqPCR98Jq65TAU8iNdUcvDqu2KbvUrxfS7+iblg",
	"XUalXBgYByMEZS5abURrKO9buaF+ElAqNoTKZb4GziFXkMBZUxFTGWMxA6I2QtP35vIYwZOzJHY6ckXW",
	"1tzuZlIk45m5DukSskxMzY3igN4bcsNkuQiSi5hJQsmcqhXZi9Ds8j4cgHqTyqtj3qI1Nx8xW5rLe4bb",
	"hcxGmEwsF8KJ3XahA0hdLlpJSom2B9vctaLbKdWrN1mvvrnS59l7w+Bh9Y/edXmNmzolQVjx2SNuzNw/",
	"yE6aEi1zZo6uYEPCNK8o7x48tdCWG/iUthitCmfbh+oRMfODhYVqMNixxNaAw1fYbEFRzZW1JMGvxdKH",
	"K3oqtpAAQW7nBqi1DBRsAZonCcj/xbUsQA2ccoQ+Mh8J5lDKvqmBavCOaJ2VabY6OcbGa+hxS2aRP11c",
	"nGIeW0MJAmw8nUVSt8WBEmdslWmq2wK1M6rUTSrjNgYMvxIbJbFCY2FzXUU6k2K8kLfjFc9Q1/azVyg+",
	"EPRyxTPL6FqmsVFZvpk3RydqEDAuXp5jMJYz8Q5auhn9qj3ktjm6jZcdNnh61Va/Aj7tBvq5YrKdR3Rf",
	"e+caYO8sMaBbmlhpnQ0UJwSuZJhAYajCaZCMmF+dCIFy6AOFRMSmrNepl7vHOSkUyYVtrnJYimLmXpb8",
	"3Y3kWjPx0eKIbIojTpqgaJhQGxGRDkEFayWFNi8Lh4u3Zy+RVEbp2pD8hbbZquZUwdcZOdEkosKyMYz8",
	"K2eQ7VTSNdNg4cijFaHqgFxO9g1F3NfpvtOU/w1afw+t28zkrSJPcXz3L+W4G9lG12+pC1hVnoRObqRs",
	"6Xl670SHALcWzj0lEU0S825GSSpQSg3eJHD7x4TDLXfKjIf3DVnBVCSYG991NewvuNg7Ob486hl5q8Ds",
	"AlGM5oK7m4kMMMhJ8HbZVTt+c75xB+wqRJqzMEw1rIQpy0dDaOCKJRnSMo0xg3ZHRdUVrbPCwrOVHmXq",
	"n2voxpys6ZK1Fe4b7GnhDfBzmuRrVivA9/uwqq9nPj111I1ywaQt2VpwRX6dQhpdDcpi3FbVthUsp3mS",
	"lErvMgftyeJ1qk9Ry9rIRusKjFS9cR74fR7MyN+NOKKYhm+HyQ3dqAfoVYQb5YpkORgCDAnfgFhd6/Xa",
	"fKl0ApaSJpLReEPYe7Byipa6MjjnZFrfDIw60LHHwKcYx/xRG8v8ZMdzIA3cjoPWy9HpoV2O5qJOBhcx",
	"bvYN1JDzA+rsE4dW9DdHJ3ugSeFUaAt5w49IzRc0CnDAWeUa9W7Ku3WwIxcR2o0t/QtDZbtkS660IWxA",
	"ftZ0Y0gWbWCa6ShSTBBpbZlvjk6KwUCeT1JDORWxWtRUrgsKatriQMpPbD7klXX7DZ4c1CW6f3KF5ZA6",
	"Ckr6BMmyZLcpm1p6q3XnObELGkjLoPEQZrd/nyh9m9cZ/Pia9GWwgN1WmvVumadWwIXCgO7X+h8IQwqZ",
	"5ZmUqXzVFs1sZocWxMaxudBgp/ZaUJ7kkrWIAFpujtI85DX9usj6bp4iV6heXZUpY01vXlFNeL6upulp",
	"wZd/hNK0HIQIxmJQMcLUm2JJ4VoeVF31H1jh4QRbA+FjAUexreOCm612XqF79yKfMymYZuqcRZLpbhTd",
	"FXpMJwpmG2oqK1dJsGPAtG5uzi1l2ko+WpzAk1th5Bbl4jCAlGsODqAyGnWMAp97hwpTnHL4qQehXmcA",
	"27s8pNDVAZeJsO9hSbJjrjQXkbZZCqfkZgX6dxqtCIfSc4qgckajEvJycsU234MR4nKCNezYe7rOEoYZ",
	"8wurxfeZTOM8sumXDGeRiu9ztceo0ntPDIA4k9/PaXTFBBCz4nHorYdRdQYJ7Q7KeTjfEutgCb+hEgCS",
	"2BXe06WbIMG7rfKkLAT9EtM3ojujjlal0hyNWIevj1k8I8/Wmd7sizxJarMrm4rO8Es2cDlQl9obte99",
	"fFVvDxVCipV+VMrKNc3Mxn+/YpspnPEHtDSFk203r5xzuwt6VZovXjIK52xjNfMboVdM86g8jlIL7tui",
	"zM3F47imkqe5KnxWYBlqRg69+uR0g2p0EOtTDCX/vXTfmRK3sA/hICEu8gDqv0LG2Nwf7iX+MX9TkvA1",
	"L2Srsh4KXO9CE4emTV7kW69kB2USHk4IdQEIFZVU/LxBkGuE/itnhautUy/oFNOeFky6y0pt+W/PHZSi",
	"uw044XCFZMG+mZxdo0JDsPfa4UpZ06UA9xGCCauVRalQXIHSEcYyy7IepdYDhDmQ2Z1WNaJm387kAWWO",
	"JCRRMsLJgt04wzCeaUaVMqhnkRZO3LkXogKmWlQN7ZawT3e0tRRMPMbkbImDlIW0dRrjEgp3QFwbm5Jc",
	"JEwpsklzXI9kEeMFKK3iG9KYiSrb1cJfrSkXXCxPNFu38FkXlRul8rkyB2vkObhcdp0AeHwwDYEy4Lc6",
	"0BibuIN2W4EYpqKnuyxO6IstQYMAJrDrOsoG6oX6PS/24RalSI7V8uCeIiDNMA7oCVtokgtAHhGTdM21",
	"Z9FWTHKa8N9QQqwsFM4RnRbIQxv9NGcRzRUzUidX6Ga2ygVYftPyK4DApiSDwovQ6FG5H8ks6PAG1veE",
	"GykM3bfaifPZTpMYNNdUkOsnsyd/JnGK8WRMe3PgLTccqDDHaDZRqNvr98bs7E9Mab4G9eWfENv4b9ZR",
	"zxaQhUVgNr7C2d/MKxlQyraxUYsJ1EAWHgNWs9FbhC70ZtSesyZTG7RaYWl0W7TLp572yceCpODUHkI2",
	"tBu3ZXQrrMpl6QkgIPDK1pKPnBju5nWq4b/P3pvHaTKdHKdMvU41/B0U1DAComVfljfDNlCazUxcEaB7",
	"eKQav2hA6G36XRPsqotJRAamdAcYHhVRP1ysJXaCXZ80OTvMr9Rb3u8PVapv61qDBvyeB3GzCnXxzWBy",
	"lU2iSUIy88ZBIvMgq4SU31J8qLnm3mpMH4htUUUTiDMSItW08Ky9rSBeNAZSYc2OXjbLBhmIbHKxC75m",
	"StN11lGfxIxlo2BuDL+AUaPDi5LENunYtnNZMh9jFrPh8y2ZYLLFVeCQ4BseFW9oJQaIFipSUo5S1uhU",
	"UOAPPfPJaZrlCfVKUqP4PCNnjMZ7hgMeWHT0o3Pfv0IxwoY2QVlFZNiRoIHZlgqfX03lkgrzRJl2hiVe",
	"ptL8+VBFaYa/Im1/VDCek1sbV22oW/BhuBEsKFJ6MVhUk/QGPD4xzQH8bkQUIxxzEe+buS4nVm5uYfYq",
	"7GrQ/coy934mP+RPixp9yEE/UF7snWV/KyF9w3we6jkmgzCoaH18Z+Pakz3GvO0u5m3YnS7OJu489gpX",
	"gOFvMH5IgfQGcbIgXGNA6hhaPoaW7/toEQzo6owx7UO0sMK23qIaM+5/HUPHP33oeOM8BslKFXI7BpJ/",
	"qYHkDfLRiewQnlvqzA2yeV+buB5zlSXUpnasD/wT5JAvckQD+6BW6Y2L9pJhWLH3iJ4ngev3zH4jJ8cF",
	"d11b4ADe85TqaOUVTy7wZQsXxd4QAa+yu6/AoTGmL8oSNMNhIqOg0ibs2X9I/vv8zWtymgIZA9/+Nl/E",
	"vIWRQ5w1THUMam+7mlnj1qVZVwBdnWKcMhkZUh3yBSi/OUWopR8otVQJSFY2xlbBDZ6xhGp+3eK5fFYt",
	"eI1N0czrQDYkqvIw0NepK528+zrVVk6jwvq6wc5MeyfEp9dMeh7PhQ1zomS0z0XM3s/+qYbd3ooDa2jf",
	"xVcHaj/NsawEVrpbueTaumcGb+JZhz92JRzUg/mPXPu+2eDDhT61vvPoyDqMTP7I5O+XSLRdEimv324z",
	"SZUDhyWE6veqfFB842OOuD+AeCBrxzFIOvAo/igbfKmyQY3qdCB5XS6ouVFUmYphscf1bCG9ccd+OFFf",
	"43O1Ktv2bL0lj029xXbJbKoQ+chkMtXB7rdMpTMpHiZM6rM8YSEPZG8HtylpRM3Y4XJXeZsh69jdPcfj",
	"8rWtFlv6btJrJo0QkSsrd6Rz6300ZwuD9DCxkS/IczjPg+40E/0JJLqSR1xexv/Zli9iOsk6hKcLTPDr",
	"ZKJ0YXfkl3tTQUiijQ89bK+Z5Lo/ZZZ/3ue2U5EeupJIyo3oHVNlH1UzXe/lqkwWKOyHXxt3xokwZfUj",
	"rzgS1EQeFkDUupZy4NYm3oytbXAp3qZfBB/Rs+JdNM8GYe+zVBlGg1PY9uHpib9pr9biOdZMd2qNQAWk",
	"ouiJq1dSKTpUKxsymU5qOfRaJMOKx4HVCbUWijk6fdtKsbI85L4wnRxzddWa7Yqrq3AvdO1odRRpdfxo",
	"FizxPTIGVyxp2U3fu9W1rp68Xy2QqNfqqPiXNA8wzAic+3FTSPGwOfoMtFtmqXs1Qg4/5jmC1zIBvty0",
	"mpE3znMWf83Az9WiPlcuodAWfGz9+Qqws4qus4SLJUS92CrXLa/NnOkbxoTbP4GuZt338IAUqYc6sg61",
	"HfXUP4rAjruoM5CDVkJlvlY1PxW7PThBW89aDNiyoX+FZkinGKEPfsCW+IH0x0cD06glGrVE4XpO2+qJ",
	"vJ671hR1FJlqyArobN8b14fNwNMIwnqckxlXpEJ38AaEw/ygdqf+iaqAWt/86jhJ9MiGxh0ld3ccYBmu",
	"0NYaY9kLMGilIK1ObqjP9gDrCiH0QDmtHGFleX23w2kSR2r+ifWBtvNGRFvzUcALjBrBL1cjWHthOtm+",
	"mlbQFaZ6qB4VTB0GJHWqw3rS2RZltap567hoZMc5MS2LFpiMpOxQor2mXGCEXojfxNw3IjVXx/XmBqef",
	"0Whl44SrQ6FvtBvALNhnertx9X4zXQ1Jyeu8vIvUvE1I31VG3gCX0n3/bqGY9ft/pGqW3o6UdqbXdRpK",
	"LM/cFohUMCxkZRgZ0APeUAXn3xKa7gb+sSM4oBjc8/0PjD0k7uoWGuZacdf7SXRRr24b4sAEu3kT9tMH",
	"DGU3WByNPORF7pV5wh6ZaUSeQPjq5EDLnIXUvgbN0lx1TOCafMQs9pl7zlkSd3AGEPpnAyYgL67tV5KA",
	"krYUV91BEkMZimiOhsQwMHaswndW1x28PJiw3tY7YDbSsCuH0iq9gdcJ2hYVA8xt8apodOkwoZjGuY2i",
	"aUPyaqOmUtFVRBmuUayN2AEMP01YoBoLfnZ2E7tpkuGv9fIFdRSELGKILBdlJvBOxWRe5q6Nm8c0oHxH",
	"/XA/wPnIHPb1Qx4vWf8i6u0h7SPk2btYSaZWaRL3jeG5t4X9slztBHuyQWQuKuGAkJvyCPPIIWDspbSP",
	"bvVkfKJVvQohFDtXqx2l1D0//6kro24m+TXV7AXbnFKlspWkirWnxsXvqAJVq9Oi7x8jI25lSb2Za+3O",
	"AUDDk9eGLo5vrN7OCVX5x9xjD7+jLJlm+zVXP5czsytXZleWyHJXISLXxhhaZpCjBlrnUlhp09y2iCaJ",
	"fdjiVDxwKWoJ5qvwQvxG3cTd6iaiYFXe83y5ZBBiDA6i9nAiV8gW4IdM/JQ8JnzhMhbUudFvngY1gaNy",
	"YqfKiZZ0b0M8PUpJDOHonOVbZGOqwi4laxqtuGCtU92sNrUJzEFbLvZy8hzzzl1O7Hpsng+uylQ3bJ3p",
	"jU3NAZk9qqJlmSDnkJzBMkmUUImxss7P2W4WrvE8N5SHYY6Q9JpJyWNGWjTOqpvEucCHAnjkDWQaOiCX",
	"k3Nkai4nJJX+Tu/82hhuf4+KeM+CtJfkh3RUduOWTBQ3oLx0oQfhorc2YK0WYMVY6YcwF3XcxpdgtDmO",
	"NkfoUUOe7cyO9c67tTzWRg87qgcaVb3Vaw1GLvDTW6hCRzJItVp/CkZD1ZdqqAqRpT7cbzixV95+q4Jp",
	"ZwFAJxYWgrHU6M0qVV4tWIvvC/DNTfsZIhx/yGYL2jssw7hfDLaRTnxrZ/Qt02t3WjvsrT7UHRmRKtl4",
	"C+DeUIWmCocYA7MjbWOaeDftuU+3MD8VG7B3bwbny9fsf1OX7NxVdniZokdxbQ0GJr+lgpXZeaSyToYw",
	"28nh60MXVXt49uxw/+Wbo8OLkzevXbJd82OVB8b0lOakU0nSiFGBb4jrWdRihEKMVGoe5QmVRHFzElyv",
	"uLUTUcnoFER2G+BKDtdM8ojuv2Y3//ifVF5NybPc3L/9Uyq5c/fMBV3P+TJPc0W+2YtWVNII6uu4vWLq",
	"W1UUdnx4Ofnx1cXlZEouJ28vji4nj4LkCfXU59GKxTZwoW4UKF9sZVu5ek6pOcaIxOmNSFJqyxLG9rop",
	"P0Os5mv3NbX1NoitkhngJXpV1UeyWlYPeC2pf5Q0YsdeOMRQnbv2Llfn2+naNWh0mCh5LFF1i9dtvNKP",
	"XPskN5yirQVR3aDvPmC28FxyvTEnu8ZJ54xKJg9zdCXAv547evDff78wfCS0nhzYr+WUEPb8YTpJ5fKk",
	"pa7b27fhhAOV9FyegYyQVzRTthaG36FMsDcTFCtncjMJJIp22ZEOzFL+wT31Mc34C7aZfDC7N0TG5Qum",
	"EdwntqY8mRxMNKPr/1okfLnSkU5mPC1HNLt4Dl8gg65ME3LB6HpiVbsTxz5Uejcyrf1SHeLdw1C3R5aT",
	"snW10b4RJVRiHL1Xejtd4NMJxJHFy7Jwus3dyiVU0jQYqDD7d8IjJtDGYHd2mNFoxcjT2ePGZm5ubmYU",
	"Ps9Sudy3fdX+y5OjZ6/Pn+09nT2erfQ6QTzREJBfA9Lh6clkWt7pyfUTmmQr+sSm9RQ045ODyTezx7Mn",
	"1rUB7qPhpvavn+zTXK/2o0JHvwxxED8yDRXkMBmwK9tR2mFmRTJNngpzQyfmnlsVOSR3g7S6MO/Tx4/d",
	"3WDoMehVA9n/p9WnIc731gIpZ4GLV0sb8sKA4Nsn3+1svkI8bGYKz8ElpyyQzWI0pdAlxO5UoYdEonIC",
	"towVaz2Dn20Dg6+1s4DMyuEzcL3g5MuCEr8Eq3EGRjUEwi2tIAUrRmMgT+5+53qVSpepZ+oBs04y393h",
	"ZWg/nAvYCWwDbsS9TPoDjYkLa4JJn9zbTrko9/rpbv908ud7AbSrBGOFWvJMylQORr6ojE9TGJ/m5NtW",
	"TAQlQGtcW9WdroqRpmdrR9WHo5AC07JvRUODoFjDwfnyQRG1QpK3FTW9NPmWSYARzACQ/RYzGut6owcu",
	"L/wDm9nbWigKj59q2vQWXqGoG9BFGqahRLA2eTUG3mjJI11mOwdHYZvO3uXzxTyvXNrqHdWqclAbrqg5",
	"EVpoUqmjcX+rRbemqZMfIDm7zU1tQHzFyIPvH0zJg+/N/0IJ+H/7/gF5yGbL2RQLkDzBCiRPplds8/Tf",
	"8I+nVuoI7RRmvN1O/TL6fpZ7vHjFJv3c+2Ve/YuyzgEkHsKk7u0XrdKd8EX1lkMmIxy0VsBgTTeYu75e",
	"p79EHIjy8koGAIRabwZfQwKiEk69Vt07fexaqQjomNuZoS/36XsrqGVDmH3lv7mHWZ+ncs7jmAl87+5j",
	"ynMrtbwVhZG38tq1vmgQTZulIRvEEdanowOetearhp27Ar3tAn5I483dYwDCrBTNtczZhwYqPrmvhYQA",
	"HY+4eNe4+O3jv97DlEb4TDiqm/742D+I7d3/3Tx5H5BGJEwHtJL4e5VaEHv3SYn1VSpxDJ26qESvgOqH",
	"mvQTKsOH4UqLRx3iOoo33RaNq1KKP5706l7urwZxv72HKV+nmjxPcxF/Lu92UBKVjGIBqZLFjToQrIqQ",
	"PzJ9z9i4RH/Ij0fF6SQX/F85s3Vz4IX/NOz2iLAjwrYw2lRH4dqu0eqWjDb0vWeczYpKW7t6QIeKAnsw",
	"9X9ud5qVxNmDBIFPTCRGGeCLokyj2BGkhXmQeYGc7jX+5Wgw/3KG/e+ZHpbpSe6dIN6bbuSTksRRNTOS",
	"5ZEs/8G0Qfs0y2RqEw8GqfkhNMAUKExsujjcJmOLbnCtHQ7d5Duj6FjG1l/wSNFHJnekpiM13QE1tR6C",
	"3f4j6PLe5yxybIcaPUNGz5DRM+SL8QwJ3BGb5YMsEro098SWK8cscGY16zWVm2qIi5qRv5udAKhSAqyJ",
	"8/JGsAAkKwnlAPPtYF4wiI1zAIBDnqQHeJsq9/5BCaN6vMONWccDO7AZ6gGk75F5K+p7bUO3rMh6cqd6",
	"faSvo8/M1+4zg/g0xEGm9m63ecMUZQzuQhiwg9+zn4s/66g5GZ1aPgV6NrnsAe4qx85dpRd3sWWBu1sp",
	"G2qDj94nozT9ORmzvRewPQSsH4N+ZHpn6LMzd5H74CFH3Blxp9/roxd/oOHOMGh03tghFo+M7ajE/pJ4",
	"6Ra3DLTFDaFV1gFjZ9Tqs3Ct2Eb2vj/qNMr5IzkcyeHdqBb2YwalLFSRTCZENovsPKV6HlUAXt+muqH8",
	"uEOlQznoZ0FLfSiMXN9I5r4mgbGd6EgmYgY40JGTB2192NBLe9dQyZzZNrtUzYQmdwbVsgzvrijQtLUS",
	"0JVIb0SxkJ9d0rqw0REan1XbTv6oiqOniB712wyJn8zkI6kYOaJPQ5zK3MqdpMlPKzlcc3zuUqyP+uNR",
	"fzzqjz398dY45WmTd4ZVo055lC5GcvK5kJMODe/W1KSi790ZPRm1viP9GOnHKHLURQ4mZJokayb0gOTE",
	"ZeOKU3NIyHhWNC3yEw8mYXRgkDCGXUCedkG4Unk1MQtU88pkes1jFk/9NOPWYXvFoivC+4LYrF+3Ck8C",
	"/tvgK88ViahihUs5d7ob649fhwiU8KBJYmsPmr5TWxWkgLI/Ebrlw8rnDOuStcZ7KPnJ1C2Ngx/p6siX",
	"3SeVK9EnGDbW+NwTQVbe54GZhxsdxriyMa5sjCsbMw5v+XyOmYbHqKnWB60vgEp0vFttwVSNHncUV9Wc",
	"555DrFoWMHphjdFWf2Q+dYsYrO3QH3uF0H8rrWP7lGOU1ihCfu4iZFfA1nboVtGO3QmufSYm+UHv8Ihz",
	"XzPOdQd6bYd30OmOMW80298N9o8M+GiB+0J5/p4Ase1onHUeuGMq91k4E9xSzfBJCNyo3RiJ60hcP5FC",
	"5RZZdwNEOVAYGHvdAS3+7PLqNrZQ5Br+1DTZLaRf6TNSyVHq/ePQrO1jQz5eSXU7Z9RRVTUi7Vevqvoo",
	"XAwrru4CG0f11ai+GsnQKGHtTH31UXSvTZl1F5RvVGmNbNDIBu1Udrk287RKKGdMS86umSK0cKTFLrNL",
	"EXasxgH7nKm/Gn/d81RqksqYSYiBsRUJwH/WbIivmdJ0nVV9pR+YMR6Qh4LdGBK44FLp1sXB4JVFxTgU",
	"VCdX0WQ6YSJfm8tA4S/48d30tr7GeP54buaInLNwnx/6bopDfNFe+HcqHJtjG/2Uv3o/ZXMNqm/AImGs",
	"L8DmuWnTF1TzHAcaA2nGQJoxkObLLdB0YmNn2yoxuU0DXWlbCY1tBjZ1joN8usJHQLbGl/Frfxnhug4p",
	"e1R9C9sCdaDVHQXn4Nj3HJDjTTq6qYxBOJ8AMxs86/7v8N8P+5qts4Rqwxopnop2ZhYeYteaFM1D3OyF",
	"bfVz2ahXlQnlAt1z2JimRXG58CjFLTOAjjz1yFOPPPUYnG7obI1ujYztyNhu+3wOCGKNXSHB+ivXErha",
	"u5Uf/Zje3VtaN0kOnHmMjh3tfvEfUZoN8sGS0RiZwOIF7EXkH5kesfg+sbgO7RGdv3p0Drzhw2v+9imu",
	"sKFTXG3lt1MdekwlMWLXF/RYYr3fPuz5kekdoc4O3e2/DuPNiLsj7vbWG+7DX2i3IwweXfR3h8Cjgmp0",
	"y/+CjFh9pYb7yJT1t98RofosPOq3MHffG10aLesjHRzp4B1oMvqCpkFzWUYrVXWYjiqGJbPbhSTdqXw2",
	"ikajaPSpRaN68avhgtKuEGoUl0ZxaaQknwclyYNvMsgkWz7LviSzK0oyyjMjNzDi8FDGG10hB0X/xlxp",
	"LiJduCxi3yKotUT2Eh03GWsLE36JMw/AdzOK9SIssFzahRWLkOm6tcw9F3En0rvgWFthckhg7CFZ8MR6",
	"2NbXkopkgz62RbQc0Svq+9Eu+TUT2L5wDb0Tv9MdrBJdLvtWuXOf0fK64XrvJdr4dsIYe0/XWYI9cLXP",
	"8BdAamsfO5jYH0uPVYM5iUMDcE3FeP1rLlOxZkJ/n8k0ziONjjaSLXkqvs/VHqNK7z0xG+BMfj+n0RUT",
	"MSL2MBoCyDf6hX7tfqFw+aoPQiqXVPDfYB3bZYWo9JwR8sYQGERZVf2IdMbgcK6YJCuqCI0ipgySh+OK",
	"31RWdYc8kj/RiB9fK36UNBtC39Pa7XPo4/9exSLJslRxnUrOesLqz1zLTV9s/Zk/5hhhP0YDjdFAYzTQ",
	"APJXUpjxQfvaGb7iXdoMCXMPvE1tse5l0zsKePcmuOeo9/rMo4F+DH3/VCjbwmJuEwIwCKmxdQWpt1LL",
	"ByYZIwJGZfnnpCyvPZUdYQGDMOpHpneOTp+JF0r3Azri01eJTz2u+oNwynph7BirRleUHWP2yBWPbqtf",
	"GiPe58M/iH5Z95edU7DPwgVmW4H+fqnWqEAYSeVIKnevs7AWro2Ieu1i2PR8I6J+y1jZdjSNjaax0TQ2",
	"msYGvswl4RiNY6NxrHydhpnHAk9Uu4GsbHxnJjJvins3ktXnHrnc0Uz26ZC3jenczlI2CL+drayC31uK",
	"8YGJRnvZKGV+Xvr92uvZaTEbhFlgM7sDtPps7Gbdb+qIWV8pZvXazgZhlzUc3QF+jRa0neP4yDKPiuEv",
	"j0vvt6INomSFHe0OaNlnYkvbVvK/bwo26hpGwjkSzt2rN2xe+DZTmhG3lB3aS3vfELPKbP53RicGpLD/",
	"SvXO7hDfQV+06+CblctkcjDZn5h3w7aun/Abd5SYiMHQBCa03cLMS9hc+TBpGqS8gVJBjpjUfGFas3O+",
	"FFwsLYGr2mKdabJsrbC1LMhh9zyYciE4KKaj7h3hWVHevmuFzSL4neMaUNqECVwsXcF7bzioody3tEDJ",
	"5Ep5i22WYLMg0EimSpGYLxZMMhEeHcO6txndD3sODlkJde3bd1tMqx3L8w7oH6nNC6AYy6OLA3YcMQ4b",
	"DhBFO6LDxg/vPvyfAAAA//8a5Y/OAzQCAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
