// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9i3IcN5IA+CvY3o2QNNtsSrJnwsMLxyxNSjLXevBIynO7pm6MrkJ3Y1iNqgFQpNoO",
	"Rdw/3B/el1wgE6hCVaEeTTUpS6rdiLHYhWcCmch3/j6J0nWWCia0mhz8PlHRiq0p/PNwrtIk1+yU6pX5",
	"O2YqkjzTPBWTg8kZyyRTphuhglDblix4wkhG9Wo2mU4ymWZMas5gvCw4zsWKlb1NE6JTQnGcVBC9YkRt",
	"lGbrGXmdakb0impCxYaw91xpLpbY9IYnCZkzkl4zeSO51kyYFbD3dJ0lbHIw2b+mcj9Jl/s0y2ZJupxM",
	"J3qTmS9KSy6Wkw8fil/S+T9ZpCcfppPDLLuA30LLNq1JuoA10ixLeETNV5hX5OvJwS8IXMUm7+qzTSfv",
	"90yjvWsqBV0bCP3iZjtynXABbtyjVGgmtFkLTZI3i8nBL79P/kOyxeRg8u/75THu2zPcf84T5jp9mHa3",
	"PWMJ1fwaD9s0luxfOZcsNuuCk3vXAE9tfc/E9c9U4lFXDp6VH2gcc9OWJqeVJrWjmNag/Uxcc5mKNROa",
	"XFPJ6Txh5Ipt9q5pkptrw6WaEi7MulhM4twMQ2QuNF+zGTGHdcU2hIqYYA9GoxVZ50qbOzNn+oYxQZ5A",
	"g6d//oZEKypppJlUs0lj2y33xIHhVKbXPGbyPGPR8LMKwNGcQhWQtLyNPWNBsw/TiblaLThXTkhMqwIa",
	"T/6//+f/rcKAJKlYTonSVGpyw/WKUJIwrZkkqSQiX8+ZnALsolRoygURKblZcc1URiM2G4Rqv09SwQYA",
	"6mRNl6wN3H23/EQkXLT3fvfhXffZnmuqcxWmCPjN0ANKFBfLpApjS8tids0RJI5EnEqWUUsTzg2I8Z9n",
	"uRD4r2dSpnIynbwVVyK9EZPpxBCIhGkWD6cr1R34czY+eotofCtX1fjkltn4UK678cnbSBXQP6dJjje3",
	"RJ8quI/ZggumCIXbG5Nr6EFyxWIy38CbVCXJVVQKI8Zbwf+VM8QHS9j9cc3d5yJE75v326efMNm7j7zz",
	"CJLGhQ3BrU6CqlvHHanm7l9ypeH+etfWNjZ75Jqt1QDaUzvDEteplHTTSz+xG96PbizbyZG/bpx14DzN",
	"cS6YZCJiIU7IfjKcC+J4lqQbFpM3Ryd7BkYJp0ITbk7RUEyDXgsaaTKn0ZV5qDrnDt0lfz09JEud5+s1",
	"lZuBpCtJfCCqdrL1I6OJXm0m08kxW0oaszhAqrYmT9XVlnO0NvEmb20ToEzVBsVyDehyvTpKxYIvm3Ay",
	"38wbt+DL5vWiuV6FwQvdDByCN8v0e3v2sqXb27OX/XeimLocLXQrfqA6CnDg8DPhwMezhAGTxQWZw8+K",
	"/Ss316y534SvuQ7zFmv6nq/ztWUNzJXPmIyY0IAAC3ublMGXPIupZsRSVZjTTDWMLp4WowIxXXNhpp0c",
	"PCk2z4VmSyaRV1UsYZFOZR8Ne0nnLDl3jU3HPIqYUhcrydQqTeK+Afx1fWg7iHML2ZYDcZ9JbB86A5/E",
	"UmiAEwJwzgh7z6Lc8L1cdJyXap3vsDouzghs+nC6j3frw9Qcwgl2eFIn/FNzf6lmy03faGdpkqS5PnfN",
	"6xe+GCd0zY/MnhcG0dk5Xxp25cxsXQUua2tTIj3xlkj748IQb6L4UrCYRGVfspDpGg7o6DBAGDL+M5MK",
	"ZmyA/vTEfquc8zX+xmKCEMEHiqtyWZapXBikxa3PyDmTpiNRqzRPgBm/ZtJsJUqXgv9WjKbcQ5VQbbZl",
	"kEQKmqBshJz8mm6IZGZckgtvBGiiZuRVKg3WLtIDstI6Uwf7+0uuZ1ffqRlPzZGuc8H1Zt9IBJLPc51K",
	"tR+za5bsK77cozIy8kGkc8n2acb3YLEC79w6/nfJVJrLiKkgybziIm7C8icuYiBjBFtaUa8AmXtpz56d",
	"XxA3AYIVIegdeglMAwguFkxiy+KkmYizlAsNf0QJN1RT5fM118rdFwPnGTmiQqQgWSGti2fkRJAjumbJ",
	"EVXszkFpoKf2DMjCwFwzTWOqaR9OvgEYvWKaAiZb1rKrRyt2WVltogom73bDYPfGa1jim70q3ibtyrei",
	"G4Yv3oJ2ABsN99CR1damI7G4e2JRPF9hYafzbAY9fe3vzYfmCziSrk9AusxZI+HajlTg8W9FK5zIXT3f",
	"v0uaZcxIfmkuYkKNzCr3IskMUMnR+dmUrNOYJSw2AtdVPmdSMM0U4SkAk2Z85vEbanb9ZNa5hCZhYe8z",
	"LlH1wqJUxCokyEJ/VKAWNOOaJjzmegPcD9yYcmIzzSKVa6qR1/7m6aTJek8n7L2WtEv9W+BZ44jr+FPT",
	"C5uBCdV4uZhygrwBL1oKHIyBOTNwztIsT+Cn+QZ+PTw9IQowxsAe2pudG7rG1+tc03nCAlpgvEhBrvIC",
	"JBnF/vLtHhNRGrOYnD57Vf77p6Pzf3/y2CxnRl45Tn7FiHmZZgWvyVkCHD3170MXw4pUoXIk841mIcQB",
	"Fla+DipETkSMlwzWJIs7gX2Q4AOp+ldOE77gLAZ9WRBBcx4gdm9Pju/hnLxFKLoMqbvewu8AdbMNoL4M",
	"3oQrtiHYy9u/FVG5UnmV+688FL0X2Gy5XxN1D4CpkUJ3myuXYzvS16KyKy8UzTKZXtNkP2aC02R/QXmS",
	"S0ZUoX8qdulZE1QL3AlflIZA1aR4XtMwjtohm/LctAQcSY0MXsB8EHYZ8oric4BrLL6hns2cbOpj2oz8",
	"JNIbQSKvoWTkEEDH4ik5ZoKb/xoIPac8wUUN41TcmEGlrH8bvC0E70AxUPsGy+OLmaY8UfCApIIRalBO",
	"u+OOcimBA9HmTB3vai71mUfSaronqvSFpELBTBe8zchl2hHN1wxnKpami74sRr7IrMteQ50SKlK9YrJy",
	"2oYB2jNjhTkRZehFcxU/5msqiGQ0httk2xGOOGH4OgcdOk9zbVdcLC9I0NI5oHv8ggmG73R49zPHysyW",
	"RUskKlVo3FAFlM+8WTHJM5zWf9f/8m3wXZeMqqCgQh7OJWeLRwRblKyDm/OBGrTTgQKiG9UJhG6kgd3Q",
	"WFrDAI36VLuCaejKFQAoz78TWfptGhUYTeFSpgtyIY2g9Zwmik2J1VX7qnjzfTKdQIOtle+11dmxar+6",
	"oWs/+3rzKjSb99H6SpS3jvuShLcbR+lQYe/+iVQPdmlInvkIOlk+T1j9D0c3TqlU0PR8IyL4x8+GlzUt",
	"UL94Ik5lupRMmQN+a0Qca4bNWOSavsoTzbOEvbkRTCpYyTWP2DEz0g1XRnYwnYYB+5mQaZKsmdD2zfR2",
	"2PquDmlTgKe1RQG3M5aliutUboJAM7Bq/dCArP+xgPLzhDHt4Ad/hOCNcPSgjj/4sMdfhp4AXsIFX9bN",
	"n8OMCS+4DnTv8yj4qeDNz1kkmb6FO8ItZv1R6yzUDWCQ5e5UXqXCHHTTE6X6mq6xWb+jU6l5SInt1M9Y",
	"+qMHbeDdbknNneAuZSqevc/MXQqzITIVhBUNCL5m8BCZseM8AZ0KXzM1uxRmk7YFV+TXPxH7/78ekD3y",
	"igsjWx6QX//0K1lbee3x3p//OiN75Mc0l41PT78xn47pxgDtVSr0qtriyd43T0yL4KcnT73Of2fsqj76",
	"X2aX4jzPslQaIcAcJNWpWcSeaXhQiJSGN0Y90kM2W86mMAwXZGWWXIzHrpncwG+PzLy/7v16QM6oWJa9",
	"Hu999ysA7slTcvjKnP135PAVtp7+ekBAk+YaP5k+eWpbKw086pOnekXWAEPss//rATnXLCuXte/64GL8",
	"HvsX2dr0OkePmup+vivBYl7O77yJLsUzdP0z0COP976bPvnL3tNv7LEGmY2jXOl0jcTlRCzSLoVFnd8B",
	"fQ4qZWMSwUDEIpk9hOCUdYHUG4QLvJAgygFrWLXDN9gMXHhzcfh71aCVrTaKRzTxxhvV0KPNarRZ7ZdM",
	"yHD5w/a5hTXqXSseN1zlmn5cYS1STeD0Xdm6fdZAmok3YQ7AeXIsnFRvrtnNikcr0E5ATzLINc5MA56k",
	"ATr6upjFtSFO1i1EyPDonlA67MzCTp0fpu3ecaWUZpsUjmeAZLV13c5Zri7AtmhnCh8wc14eQIvND7pX",
	"VR+o0KumsIG7Pytwx6p5CAZcxKrXlNuntPOa+q8dKkQc5QM1ge+RuBOVQbeDXNPdpAeqyIu3AfLI03CV",
	"cj7Cq9WdTDIRM8ni1mf4zDZwD2/ruH163+o8nZtUadLKYdjPPqNh1Rnwc5QKwSIr+ReHHXJTAob95DhM",
	"iOxncnLsK5VqM4QvBvZ85T0dtfte8HrFLI5QO9Jm1m0NBN9XQg8iKuC1VKjPBfcpmvDfUPFYBIowueaC",
	"JtNizejAZbpNCdNR23HR+I1INpMDLXNWu5q1XU09ALYfpS87NwHhBrN8J3VXKq5K3IXGunGGmsol08Oe",
	"TX8pF9AvrI7DIYdtyRunScYLcw8iizIzNLa2ZnqVxlWU8pVUbwUDVQ4opCKdys0ZU5X1damBulbsjdzV",
	"rDprAYUT8w5KrjdHKxZdtRGk9rZ17K2SLO56kMh0IRmTBiPQan3LN2Av+AaUEk99TlzRR5D+9s3fjva3",
	"jtSj590CmOWtc5EUr1N9iuc0mU5OmYjxrhVKvlOq1ODwkPZ9lBO2t6kspb1Zucj2NsXyO4axG2uCv1W7",
	"bpmYtqvcwPGsJunDLLGRTvTm9pcLXJG2ZYVKNAA2qFx0DxNkWv/MJFjnA+8oXxuOcZ25vdcGv4aeJS87",
	"zAR2K+yzEUd4RI4F19l6eOBcJ8R/D5uEQ0D5+4rpFUOO4uL0lRHKrWF4viGUAB6AlkHLHPwB0NXXgmGe",
	"pgmjYFe9ZiJGH/Ma1E9fkTUV+YKC2CvbvCY+BOIsb02TmvAdTJVa3z6Lgh61KcnEW6GcZvJ2xKeC5S3b",
	"aSMTPTTLffZWWADsJV+waBMl7Mc0vXJwchv+gS1S6VsqDheaSe9vbHDG5mnqtyh/2AYUlaU0pg60qa+m",
	"dRh/gW3jeGtuAudWAk7ieu+ULagPviu+oLbX27EEoUHa8M4PIg9BrPn2oxHRIkDVBlb9ZUscrK26jke1",
	"z5VVBL6HltbTrIaRIde68lvVwxp/V6Mi+5P7U3snMUgHZs0Wo6v0H81Vejqx6r9hJ+iYjN35WIes/8dM",
	"Q4qHY3SaairFUXnYb8rGdqBDirlptOaC6lSSLJdZqvACO9rbtZImiTXQpjpacbEE54cOZFmY78AIKnTM",
	"go41vmuob2kN7h4kGgsaCu4zptLkugPcVCGTDM3DEMc9uoaEKpKaxuShyJOE8AURKf7yyGzW/Giefafr",
	"CphM7+mA3d6DB5xJds3TXL3a5qDtGbu+ycZar+NbHjho/tMkb/e6+jG9cSrSRcIjDa5+0m7MBwCa12E3",
	"oF1w/4J9HbOWZBOdV662tvYr90aFgyb8rwQ/ze0TjdpA8ua8UAK3ap7WQbfMi8ogGJmPpjI5LOQax+3c",
	"1G2Y5Tfng7fwc1Xt77YRfrPNl2O+bA1XiOFbfSx0tCBqRZ/++S8H9PFsNns0FDTVSTsABci24tnRiorl",
	"p6Hs9TUEUV6wmw4qJ9iNpWtI7wrqJtk6vWbxMOLmSEPHRK5JeDaRCjZkqnbEbT+pwtdvq4tdMJN9irYo",
	"y4dxGtV1OKVRzNXVx/Rfs3U6lNcJjVB3oM/ySTGoXd1Q0HbfcVXxxENgVy91mTbj71Ra4etIcs0jmtw6",
	"SUdooX4OkObXcvLQV29Boc9ukaFvvtux56/R8oDUng/a4fNU2oSHJcfJrPPlrdLj1Bw+G2971JKExC0E",
	"v99iDUF/09D0Kk1CjhAXXiIKGml+XZpgre1xW+nPWZaD8X5VNcLWNkUImBi4DsuJWMYKqFZAa2CWVsFB",
	"6+FqT8SGTg6HQc3HNQQFzIAYt5jE8SPEgLm0Kp53bs3X1zB2p1RrJoXqSgWCkkhmW1Y203ATQd9Mtw4j",
	"xwIzNcVkcamE/6a5EZ0XC/5+SjCPxoolyZ7Sm4SRZZLO3WSwfpidLikXSrsQoWRDkpTGDKeANa3p+5dM",
	"LPVqcvD0z3+ZTuwQk4PJ//3L472/0r3fDvf+9+Dycu8fs0v4v18uL9/92+Xl3uXlny4v//buPx/+17B2",
	"j/728PJy9gs2DH3+jxDf1Z/4CrUFp2nCo4GPz1uvB17XD63vSrcBuGnyDetalZdzyxJPYvuuKdiieIK+",
	"WZHOaVJGcn0srbVMsU9ySzXvFvSl6UwXwDHadAnaevSaS9XwWMDiDACO6PTm3KsMHIOBcjQkM94y/s9/",
	"bwYR7NLfCQyb1sZyK/Ofs1ieMyaGxPHZa4Fha0y4OFhL/4ZbLAs9+61MA1s+LEWfytOyLa+5tVqucSGR",
	"Sjv/9gEDlO0LchVvQ6niFsdYDzMqq6pi4iSMmD4Y/etXXGM4m3K9JdS8q+bfgHbe/PZekt5dXVEZ31DJ",
	"QL2PIRtcLO2TSSoK9917T9o1uPDWXfhPBkBzO1PZVtkJw/boNxBFFU5E6Js8T9MbJln8ZrG4pfBTWas3",
	"a+Obt5DA16poU/nUtNBWPld2EPgeEIwq2D4smuVN5rwg8XZ66TXY+yxVZeYBumRCzy7FMxqtIGlClErJ",
	"VJaKGMOoS5YYr6k1dUU0o3OecL2ZXYr+uBjcROWWR2mSYK7nwlTTymqYRbbaAM3rcriEvNLYJJyj0bO+",
	"tIzhtTCvOQZnWTg1onbKkc15h3xdf0hTTU6OtxkKw46GUPZGpJN5yhxRQmiHd/mmoFznjnINXF7dKOQD",
	"tIBCcxXT6vG105EGV9zj+JlBS9ASrqmgS4zEBzqJbwbkE4+SPDZfblZMuN+dhXfOSJzeCCuRGLpuEzoE",
	"fMhsu3OMPOzlN3AzRevi3b1t/w89YItvpavGNe3gyap5uVWG3+VzVdns7Z6r5hBb+HWUACucOrKL9JhC",
	"FpE3uX6zsP/2nHlu805VFulNEfjqzxrsXPMqqn5tPDe+4NTDJrkcsM6zHvTYkulcChYjwi0YGtfKhOpg",
	"juqUJsub3PbYDchrEbMFzRM9Ofi98RYdkrlk9MpgdOdO5hty6a/rctL0UCovl6rzmH+Axds1dS9cp5om",
	"Lbpq88kLHAvNNDDPiKV+fyToWMGiCzr1CAYA1TRwWevnX9twkBpxddUb5b91YP30D5YZIPiAW0UQvNw4",
	"ALzdXF1hzq5tCs/EXEKS501Recbpcq350Buzey8dJVKOuZI5zPpDHtu4mJo6rtaimvOZXbPE5mZPb1hs",
	"lmVbI5mUmFyDcLinmc2w0QTDUqZ59sOmXd2W0DlLDB8PzLuNRyDQDersOFN7Of8cllvRP3ka2Ie/HO79",
	"L9377fHeX9/9slf8+x/7s3d/evQ37+MA3Smoet8Kek25tWsGE49jBnCP6rgzIkXPAqldlRgEH2iTOxKI",
	"w9fDnulrec8XJBfNeYtz3Gr+IA+X++mfLGGbPDYUpH1xRW5Ht44ishaj83RKIluWAyvnFB1KxtflzAN3",
	"HkogoQy/tt7jzGCPHRt850FxlwuuZ6TMW1H8CPnNDsivClNAKMxOOSW/rvEHzOhgfljhD5C/Aq63d9X+",
	"dvDLk72/vru8jP/06G+Xl/Evar0K36tnIkoNUz8kPIzZtkjnILoPCAPVtOYN6nN1WUK5EWsxB+Tg1EA4",
	"1ant7P7+wQ7yYeplDyoLFNQrLbkWe1Yb2scZl2Oe2w51yhYYM/QiNVIbNWHbaNKRZd1mCjS3ERfQaUwY",
	"fXzHZBVfYbKKBkJtl7ei2X23CdVbsp2FBIbWpmUWybDGoCAUnj2MlCSrPUaZuqxqHflKb7yYMEedVlSR",
	"OWOCuAHCUWDAS31MybtDl4wWRwJ1apYlm7LIUEsmoMbh2X1udUKerDVInGg/6iYf3zNp34l71uiPPfvD",
	"Fm9I4E2otglO/NO/oapy8MMMja7HD23ZVapJWkzbAeKTN+rU31JACplueQS3cAkIAL44oFnwroUjfILN",
	"qsE+jSYjS/DJw36CZzLIKaHJOI6xQF9q2YQww9JPA8CHk6PzZtEQqU+j7QPlPPvBUSbgaCwZRPPT5DSf",
	"Jzz6iQXIsp+wP4NmaOB0AeTO4HVx+ur/wNKp6LJ2dH4WNs6pFn/uUGUAP8m5wiyu/mMW4Byqzl7Dk5VN",
	"J+zqiMkAHf6/Zn9+/Fe39Uqtq7QMkn8m4lQqLBn3E9uQh89+ejR1edVR9rfR8pXI90rovJ+1YNc8k8t1",
	"bQVXrBLtsVFcFc5EKyaIwWTvGeMqxOR5yu9sjel2N2EQXpy+emorNmwMhcrROpxKgsCtH3N5q5791P/8",
	"mxs1DMdajHstDbd7/Ae9xSXXfyse0vOm60vp72NTM6//bOts/c3c9Owjnrqd5d9vam06Ttc26eKrV+mN",
	"1fuZlwcupK3z/Dzhy5UmR+YlShMfOzx3u2YhTENfo0I3uZUC6jCHCuS+3inne+7xDR/727OX7nTenpRo",
	"D74DJFfoE51J93j/n2fEXBFguhIurjD3LMznWIYOP4vbatbaFGw1eJUTtMJg0JUAOPZfC1fTtKy0YVmb",
	"6rIqlwbrIN7iauDQex5K7oVzsR1BQy+Z+THVtFymj+agjAUmjbqlm/HJgif4WF28PA8jPi7mim06F/ET",
	"22w1uWETeuauI3sLVJpLHHTww0nCAMrgkuoZtEhveejevsylSiXXrSAv2x66pu3Q9x/QYmRSKZTVhsCh",
	"8DoUAMyzD8QjjiVThdNL78bJQ8fLr1KljUh/kKVSDwiY7ABQsdjgyRumPxCT7WrcdisaoMQQGFxw+Ug1",
	"JV8uIaskSDxmAjQCoWQF/NMcghAX/D3yK4yDjswMd0AegoEGXH3MD+qRN4P9SnOdrqF+kQtYeRT2uRtF",
	"+B2L8HEZWtv5cJkRXRguOPdfQ7w46qeHabGLmuij8L5z4b2l0tAh4l2ZOKkmKtfTORo4ZrYq0A7tFu01",
	"gdQqlXpK1jRaccHKddrjB/pTDfOvVQ9CcuQZWp0TyxHWSPPqkRzZKmhe1RP88LYICKj+0mjokh7UfvHH",
	"bAYbtvxc63F0+rYR/Xp0+rYeL3t0+va1eY3LRq8gnLjRF3+ud8dfayMcc3XV6G9+rPc2v9X6enFOVRd2",
	"70PD8937Vo8WPubKchd+MreAD/xRo5V5hZnQDd9G+3vTq7HoUPgzdpXiaZVEawfZkhGmO5dKR6Ub88uJ",
	"uLa/ndj35YKqq/7qPe7nE0H9D375nXNNpWb1ojwl8vi/Qj33I+sHUq/0c2Rutvb2O6h4UG1l/qdgPSHz",
	"IxfLBmZWag3Vf7StQwkcsOGg1+8cm3qFxNpd3zxG6Q3W60K8mRKLUz7FKlDK4du7fitPt661+jgHSpJN",
	"i1JmuKmpZRBbOUovA0dNfrgGJxDrhucK101L1VZsS8ilAiECMJph+oMyEQeGIWeZDefuRKVOJWZ3aqge",
	"LNxi5HoWpLbUJT0xgC2JTsI42jJUoGk5ToBgtBaeqrcsR6khuiUAPW6klcbNsdyr2zOKbebxnq6GDpaq",
	"9fOUfJgOrOvVOvigwM2WQxvWu/uC3maM+lXsrzDWdtBDK28FT7avc8c1/fBuq9QzQHNaLMXuU806fA0S",
	"wWgS/uQm4eIghtmBQZsx2n6/WNuvx1gFGapiFSgKApqpLBXAMDaFwJqS0XXuV3xtOU+P7q6YN7Tn5zxx",
	"okfbnuEj2tIWPJQkOerqD67GRLP3mjx8e/F87ztQuNWKz3uTQBQLT1otYaad8zzuN3B4jtRB/3Sz/fZ6",
	"K+ZrUWGlJVyhJaUkT9gDhZEJU88Z3aoiwSfdZfMT+ZpJHpGT4xk5Rh95ILyXE5mm+nISxpI0Zp1TZ0xa",
	"2Z6YtjPyP2kOxAMXg1bctUH1BV3zhFNJ0kjTxJnVEkbBr/w3JlNXzvDxX779Fo6PoqNDxNe2A1ZhCfX5",
	"9unjR4Z66ZzH+4rppfmP5tHVhsytaz0p8p3PyMmCGOpUQGyKsbDVzQAKmH0qEnsAM8sLV9zKVWvuT4QW",
	"pKq7g4Nqu3NvMq8uthO9okLOtSn5vPQQw1z0K0N7YrP/81kxduVnxwC/syvcLljLJyO9rJePc32ND+eQ",
	"o5OdUrC5/t4MaSqoQktwE3B6Ady24Zyee791zYjHTN2jF//oxV8Xlrbz3Mcuu/XWhzHDklbxqSppYdLj",
	"EZM/uaRVHsQgSQtp9ihpfamSVof25X6yKocUmiGNPFcn6zWLedCdz/Y3l45qttwUymQ3yxyTp0OmaTdK",
	"aBbN1plB/M4cQL6AeFHtUIqJ1j/MRutukQu9voTq1gecYdCBs9lmO99Nm3OjjD+uCZ7o/AiWoDDQ4ARc",
	"tHOZpHPOXFwzi2vA6gxnLh/C8FY7vMBhK72e33arw7JtnlUag9tQwpxrTSdC0zlLzl1j7wK2YJj9Wktl",
	"30yUUUvNcC8lsOv5ccLMQz3Thdtv68XuvNG3vsqDs5JC6ylhIJDSJNkQXuYn8VBjRa8ZCMzgfQbpxkCu",
	"p4IuWcX3iwtCyc2qTYGznYNxceIfn9QzbqTl2aaSy9RhzCCOokqttvRofsGEkf7PWJYWsnEwCGBBE8Ua",
	"BWft+9Vt0MChnfUoly2Jax5mKRipN5C7X7NHkOUMrevDikOYoW2b4F65DuTgbjzNS67PzHZCa5TOvwq9",
	"Ml9wXc0+TdBtcJtcKC4DiqsXwpeOApXOBS313N3n/qe1HKrgFINjIh0/Y9e8/cmW9qtZdK5YyUJ2rrdR",
	"/rpYfGPWaVtWl2lL7f2mprmSor1/Nbawuz350MRQqC9yuq1SfVRLwbbozDaMpYZyBdzzmulACpA5I+w9",
	"i3KNsS+DKJFZWyc10nzNLDX5zPKTkAfqQTU9yYP1g2p6EiNEPlg9+PgUJR9CqZCG2brL23GWi8mHd6Ci",
	"q/4YyBly/TOVHxN29Uxcc5kKeBCvqeTg1XfFNnuVEulc/BMzdrq8N7kwMA5GVslctNqI1lCEtXJD/VSN",
	"VGwIlct8DZxDriDNrqYipjLGlPNEbYSm783lMYInZ0nsdOSKrK253c2kSMYzKOq+hFwAU3OjOKD3htww",
	"WS6C5CJmklAyp2pF9iI0u7wPR+zdpPLqmLdozc1HzGnlslOVZeJtyqdcCCd224UOIHW5aCUpJdoebHPX",
	"im6nVK/eZL365kqfZ+8Ng4c1GnrX5TVu6pQEYcVnj7gxc/8gh2RKtMyZObqCDQnTvKIId/DUQltu4FPa",
	"YrQqnG0fqkfEzA8WFqrBYMcSW6kLX2GzBUU1V9aSBL8WSx+u6KnYQgIEuZ0boNYyULAFaJ4kIP8X17IA",
	"NXDKEfrIfCSYQ4nVpgaqwTuidVYmQ+rkGBuvocctmUX+eHFxitlGDSUIsPF0FoWiPDFBE3HGVpmmui3A",
	"NaNK3aQybmPA8CuxURIrNBY211UknSjGC3k7XvEMdW0/e+W8A0EvVzyzjK5lGhv1v5vZTXSiBgHj4uU5",
	"BmM5E++gpZvRr0JB2W2jX7HN8MHTq7YqA/BpN9DPFZPtPKL72jvXAHtniQHd0sRK62ygOCFwJcMECkMV",
	"ToNkxPzqRAiUQx8oJCI2sbhOvQwrzkmhSAFrQ6FhKYqZe1nydzeSa83ER4sjsimOOGmComFCbUREOgQV",
	"rGgT2rwsHC7enr1EUhmla0PyF9rmFJpTBV9n5ESTiArLxjDyr5xBTkpJ10yDhSOPVoSqA3I52TcUcV+n",
	"+05T/jdo/T20bjOTt4o8xfHdv5TjbmQbXb+lLmBVeRI6uZGypefpvRMdAtxaOPeURDRJzLsZJalAKTV4",
	"k8DtH9PCttwpMx7eN2QFU5FgBnPX1bC/4GLv5PjyqGfkrQKzC0QxmgvubiYywCAnwdtlV+34zfnGHbCr",
	"42fOwjDVsBKmLB8NoYErlmRIyzTGDNodFbUxtM4KC89WepSpf66hG3OypkvWVl5tsKeFN8DPaZKvWa1M",
	"2u/DanOe+fTUUTfKBZO2sGbBFfnV5Gh0NSjXbFvt0VawnOZJUiq9y0yhJ4vXqT5FLWsjZ6grA1H1xnng",
	"93kwI3834ohiGr4dJjd0ox6gVxFulCuS5WAIMCR8A2J1rddr86XSCVhKmkhG4w1h78HKKVqqf+Cck2l9",
	"MzDqQMceA59iHPNHbSzzkx3PgTRwOw5aL0enh3Y5mos6GVxqttk3UOnLD6izTxxa0d8cneyBJoVToS3k",
	"DT8iNV/QKMABZ5Vr1Lsp79bBjlxEaDe29C8Mle2SLbnShrAB+VnTjSFZtIFppqNIMY2ftWW+OTopBgN5",
	"PkkN5VTEalFTuS4oqGmLAyk//fSQV9btN3hyUD3m/skVFq3pKPvnEyTLkt2muGXprdad58QuaCAtg8ZD",
	"mN3+faL0bV5n8ONr0pfBAnZbAc27ZZ5aARcKA7pf638gDClklmdSpvJVWzSzmR1aEBvH5kKDndprQXmS",
	"S9YiAmi5OUrzkNf06yI3t3mKXDlxdVUm9jS9eUU14fm6mqanBV/+EUrTchAiGItBxQhTb4olhZNOUXXV",
	"f2CFhxNsDYSPBRzFto4LbrbaeYXu3U/5nEnBNFPnLJJMd6PortBjOlEw21BTWblKgh0DpnVzc24p01ay",
	"huIEntwKI7coF4cBpFxzcACV0ahjFPjcO1SY4pTDTz0I9ToD2N7lIYWuDrhMhH0PS5Idc6W5iLTN7jYl",
	"NyvQv9NoRTgUCFMElTMalZCXkyu2+R6MEJcTrDTG3tN1ljDMa15YLb7PZBrnkU2/ZDiLVHyfqz1Gld57",
	"YgDEmfx+TqMrJoCYFY9Db9WCqjNIaHdQdMH5llgHS/gNlQDpNRgVrPd06SZI8G6rPCnL9b7EtHfozqij",
	"Vak0RyPW4etjFs/Is3WmN/tQMr46u7JJDA2/ZAOXA9WDvVH73sdX9fZQx6FY6Uel+lvTzGz89yu2mcIZ",
	"f0BLUzglcvPKObe7oFel+eIlo3DONlYzvxF6xTSPvOL2hRbct0WZm4vHcU0lFO13PiuwDDUjh14VabpB",
	"NTqI9SmGkv9euu9MiVvYh3CQEBd5APVfIWNs7g/3Ev+YvylJ+JoXslVZtQKud6GJQ9MmL7JiV7IqMgkP",
	"J4S6AISKehd+3iDINUL/lbPC1dapF3SK6SILJt3lDrb8t+cOStHdBpxwuEKyYN9Mzq5RoSHYe+1wpay8",
	"UYD7CMGENaWiVCiuQOkIY5llWY9S6wHCHMjsTqsaUbNvZ/KAYjQSkigZ4WTBbpxhGM80o0oZ1LNICyfu",
	"3AtRAVMtfYV2S9inO9paCiYeY3K2xEHKQto6jXEJ5RUgro1NSS4SphTZpDmuR7KI8QKUVvENacxEle1q",
	"4a/WlAsuliearVv4rIvKjVL5XJmDNfIcXC67TgA8PpiGQBnwWx1ojE3cQbutQAxT0dNdFif0xZagQQAT",
	"2HUdZQP1Qv2eF/twi1Ikx5pmcE8RkGYYB/SELTTJBSCPiEm65tqzaCsmOU34byghVhYK54hOC+ShjX6a",
	"s4jmihmpkyt0M1vlAiy/afkVQGBTkkF5PGj0qNyPZBZ0eAPre8KNFIbuW+3E+WynSQyaayrI9ZPZkz+T",
	"OMV4Mqa9OfCWGw5UQK125anb6/fG7OxPTGm+BvXlnxDb+G/WUc+W+YRFYDa+wtnfzCsZUMq2sVGLCdRA",
	"Fh4DVrPRWyos9GbUnrMmUxu0WmEBa1tayaee9snHspHg1B5CNrQbt2V0K6zKZYEAICDwytaSj5wY7uZ1",
	"quG/z96bx2kynRynTL1ONfwdFNQwAqJlX5Y3wzZF5f6KAN1fFd/nFw0IvU2/a4JddTGJyMCU7gDDoyLq",
	"h4sVn06w65MmZ4f5lXqLsP2hCqptXRHOgN/zIG7WCi6+GUyuskk0SUhm3jhIAB1klZDyW4oPlbHcW43p",
	"A7EtqmgCcUZCpJoWnrW3FcSLxkAqmsXkG2QgssnFLviaKU3XWUcVCSznD1EwN4ZfwKjR4aUjYpt0bNu5",
	"LJmPMYvZ8PmWTDDZ4ipwSPANj4o3tBIDRAsVKSlHKSspKijDhp755DTN8oR6hYNRfJ6RM0bjPcMBDywN",
	"+dE5w1+hGGFDm6D4HTLsSNDAbEuFz6+mckmFeaJMO8MSL1Np/nyoojTDX5G2PyoYz8mtjas21C34MNwI",
	"FhQpvRgsqkl6Ax6fmOYAfjciihGOuYj3zVyXEys3tzB7FXY16H5lmXs/kx/yp0UlNeSgHygv9s6yv5WQ",
	"vmE+D/Uck0EYVLQ+vrNx7ckeY952F/M27E4XZxN3HnuFK8DwNxg/pEB6gzhZEK4xIHUMLR9Dy/d9tAgG",
	"dHXGmPYhWlhhW29RjRn3v46h458+dLxxHoNkpQq5HQPJv9RA8gb56ER2CM8tdeYG2byvTVyPucoSalM7",
	"1gf+EXLIFzmigX1Qq/TGRXvJMKzYe0TPk8D1e2a/kZPjgruuLXAA73lKdbTyStwW+LKFi2JviIBXf9tX",
	"4NAY0xdlCZrhMJFRUGkT9uw/JP99/uY1OU2BjIFvf5svYt7CyCHOGqY6BrW3Xc2scevSrCuArk4xTpmM",
	"DKkO+QKU35wi1NIPlFqqBCQrG2Or4AbPWEI1v27xXD6rliXGpmjmdSAbElV5GOjr1JVO3n2daiunUWF9",
	"3WBnpr0T4tNrJj2P58KGOVEy2uciZu9n/1TDbm/FgTW07+KrA7Wf5lhWAivdrVxybd0zgzfxrMMfuxIO",
	"6sH8Bde+bzb4cKFPre88OrIOI5M/Mvn7JRJtl0TK67fbTFLlwGEJofq9Kh8U3/iYI+4PIB7I2nEMkg48",
	"ij/KBl+qbFCjOh1IXpcLam4UVaZiWOxxPVtIb9yxH07U1/hcrcq2PVtvyWNTb7FdMpsqRD4ymUx1sPst",
	"U+lMiocJk/osT1jIA9nbwW1KGlEzdrjcVd5myDp2d8/xuHyNXLbnu0mvmTRCRK6s3JHOrffRnC0M0sPE",
	"Rr4gz+E8D7rTTPQnkOhKHnF5Gf9nW76I6STrEJ4uMMGvk4nShd2RX+5NBSGJNj70sL1mkuv+lFn+eZ/b",
	"TkV66EoiKTeid0yVfVTNdL2XqzJZoLAffm3cGSfClNWPvOJIJ2KRDgwgal1LOXBrE2/G1ja4FG/TPwUf",
	"0bPiXTTPBmHvs1QZRoNT2Pbh6Ym/aa/W4jkWmXZqjUAFpKLoiatXUik6VCsbMplOajn0WiTDiseB1Qm1",
	"Foo5On3bSrGyPOS+MJ0cc3XVmu2Kq6twL3TtaHUUaXX8aBYs8T0yBlcsadlN37vVta6evF8tkKjX6qj4",
	"lzQPMMwInPtxU0jxsDn6DLRbZql7NUIOP+Y5gtcyAb7ctJqRN85zFn/NwM/Voj5XLqHQFnxs/fkKsLOK",
	"rrOEiyVEvdgq1y2vzZzpG8aE2z+Brmbd9/CAFKmHOrIOtR311D+KwI67qDOQg1ZCZb5WNT8Vuz04QVvP",
	"WgzYsqF/hWZIpxihD37AlviB9MdHA9OoJRq1ROF6Ttvqibyeu9YUdRSZasgK6GzfG9eHzcDTCMJ6nJMZ",
	"V6RCd/AGhMP8oHan/pGqgFrf/Oo4SfTIhsYdJXd3HGAZrtDWGmPZCzBopSCtTm6oz/YA6woh9EA5rRxh",
	"ZXl9t8NpEkdq/on1gbbzRkRb81HAC4wawS9XI1h7YTrZvppW0BWmeqgeFUwdBiR1qsN60tkWZbWqeeu4",
	"aGTHOTEtixaYjKTsUKK9plxghF6I38TcNyI1V8f15gann9FoZeOEq0Ohb7QbwCzYZ3q7cfV+M10NScnr",
	"vLyL1LxNSN9VRt4Al9J9/26hmPX7f6Rqlt6OlHam13UaSizP3BaIVDAsZGUYGdAD3lAF598Smu4GftER",
	"HFAM7vn+B8YeEnd1Cw1zrbjr/SS6qFe3DXFggt28CfvpA4ayGyyORh7yIvfKPGGPzDQiTyB8dXKgZc5C",
	"al+DZmmuOiZwTT5iFvvMPecsiTs4Awj9swETkBfX9itJQElbiqvuIImhDEU0R0NiGBg7VuE7q+sOXh5M",
	"WG/rHTAbadiVQ2mV3sDrBG2LigHmtnhVNLp0mFBM49xG0bQhebVRU6noKqIM1yjWRuwAhp8mLFCNBT87",
	"u4ndNMnw13r5gjoKQhYxRJaLMhN4p2IyL3PXxs1jGlC+o364H+B8ZA77+iGPl6x/EfX2kPYR8uxdrCRT",
	"qzSJ+8bw3NvCflmudoI92SAyF5VwQMhNeYR55BAw9lLaR7d6Mj7Rql6FEIqdq9WOUuqen//YlVE3k/ya",
	"avYT25xSpbKVpIq1p8bF76gCVavTou8fIyNuZUm9mWvtzgFAw5PXhi6Ob6zezglV+cfcYw+/oyyZZvs1",
	"Vz+XM7MrV2ZXlshyVyEi18YYWmaQowZa51JYadPctogmiX3Y4lQ8cClqCear8EL8Rt3E3eomomBV3vN8",
	"uWQQYgwOovZwIlfIFuCHTPyUPCZ84TIW1LnRb54GNYGjcmKnyomWdG9DPD1KSQzh6JzlW2RjqsIuJWsa",
	"rbhgrVPdrDa1CcxBWy72cvIc885dTux6bJ4PrspUN2yd6Y1NzQGZPaqiZZkg55CcwTJJlFCJsbLOz9lu",
	"Fq7xPDeUh2GOkPSaScljRlo0zqqbxLnAhwJ45A1kGjogl5NzZGouJySV/k7v/NoYbn+PinjPgrSX5Id0",
	"VHbjlkwUN6C8dKEH4aK3NmCtFmDFWOmHMBd13MaXYLQ5jjZH6FFDnu3MjvXOu7U81kYPO6oHGlW91WsN",
	"Ri7w01uoQkcySLVafwpGQ9WXaqgKkaU+3G84sVfefquCaWcBQCcWFoKx1OjNKlVeLViL7wvwzU37GSIc",
	"f8hmC9o7LMO4Xwy2kU58a2f0LdNrd1o77K0+1B0ZkSrZeAvg3lCFpgqHGAOzI21jmng37blPtzA/FRuw",
	"d28G58vX7H9Tl+zcVXZ4maJHcW0NBia/pYKV2Xmksk6GMNvJ4etDF1V7ePbscP/lm6PDi5M3r12yXfNj",
	"lQfG9JTmpFNJ0ohRgW+I61nUYoRCjFRqHuUJlURxcxJcr7i1E1HJ6BREdhvgSg7XTPKI7r9mN//4n1Re",
	"Tcmz3Ny//VMquXP3zAVdz/kyT3NFvtmLVlTSCOrruL1i6ltVFHZ8eDl58ericjIll5O3F0eXk0dB8oR6",
	"6vNoxWIbuFA3CpQvtrKtXD2n1BxjROL0RiQptWUJY3vdlJ8hVvO1+5raehvEVskM8BK9quojWS2rB7yW",
	"1C8kjdixFw4xVOeuvcvV+Xa6dg0aHSZKHktU3eJ1G6/0gmuf5IZTtLUgqhv03QfMFp5LrjfmZNc46ZxR",
	"yeRhjq4E+NdzRw/+++8Xho+E1pMD+7WcEsKeP0wnqVyetNR1e/s2nHCgkp7LM5AR8opmytbC8DuUCfZm",
	"gmLlTG4mgUTRLjvSgVnKP7inPqYZ/4ltJh/M7g2RcfmCaQT3ia0pTyYHE83o+r8WCV+udKSTGU/LEc0u",
	"nsMXyKAr04RcMLqeWNXuxLEPld6NTGu/VId49zDU7ZHlpGxdbbRvRAmVGEfvld5OF/h0AnFk8bIsnG5z",
	"t3IJlTQNBirM/p3wiAm0MdidHWY0WjHydPa4sZmbm5sZhc+zVC73bV+1//Lk6Nnr82d7T2ePZyu9ThBP",
	"NATk14B0eHoymZZ3enL9hCbZij6xaT0FzfjkYPLN7PHsiXVtgPtouKn96yf7NNer/ajQ0S9DHMQLpqGC",
	"HCYDdmU7SjvMrEimyVNhbujE3HOrIofkbpBWF+Z9+vixuxsMPQa9aiD7/7T6NMT53log5Sxw8WppQ34y",
	"IPj2yXc7m68QD5uZwnNwySkLZLMYTSl0CbE7VeghkaicgC1jxVrP4GfbwOBr7Swgs3L4DFwvOPmyoMQv",
	"wWqcgVENgXBLK0jBitEYyJO737lepdJl6pl6wKyTzHd3eBnaD+cCdgLbgBtxL5P+QGPiwppg0if3tlMu",
	"yr1+uts/nfz5XgDtKsFYoZY8kzKVg5EvKuPTFManOfm2FRNBCdAa11Z1p6tipOnZ2lH14SikwLTsW9HQ",
	"ICjWcHC+fFBErZDkbUVNL02+ZRJgBDMAZL/FjMa63uiBywv/wGb2thaKwuOnmja9hVco6gZ0kYZpKBGs",
	"TV6NgTda8kiX2c7BUdims3f5fDHPK5e2eke1qhzUhitqToQWmlTqaNzfatGtaerkB0jObnNTGxBfMfLg",
	"+wdT8uB7879QAv7fvn9AHrLZcjbFAiRPsALJk+kV2zz9N/zjqZU6QjuFGW+3U7+Mvp/lHi9esUk/936Z",
	"V/+irHMAiYcwqXv7Rat0J3xRveWQyQgHrRUwWNMN5q6v1+kvEQeivLySAQCh1pvB15CAqIRTr1X3Th+7",
	"VioCOuZ2ZujLffreCmrZEGZf+W/uYdbnqZzzOGYC37v7mPLcSi1vRWHkrbx2rS8aRNNmacgGcYT16eiA",
	"Z635qmHnrkBvu4Af0nhz9xiAMCtFcy1z9qGBik/uayEhQMcjLt41Ln77+K/3MKURPhOO6qY/PvYPYnv3",
	"fzdP3gekEQnTAa0k/l6lFsTefVJifZVKHEOnLirRK6D6oSb9hMrwYbjS4lGHuI7iTbdF46qU4o8nvbqX",
	"+6tB3G/vYcrXqSbP01zEn8u7HZREJaNYQKpkcaMOBKsi5Aum7xkbl+gP+fGoOJ3kgv8rZ7ZuDrzwn4bd",
	"HhF2RNgWRpvqKFzbNVrdktGGvveMs1lRaWtXD+hQUWAPpv7P7U6zkjh7kCDwiYnEKAN8UZRpFDuCtDAP",
	"Mi+Q073GvxwN5l/OsP8908MyPcm9E8R70418UpI4qmZGsjyS5T+YNmifZplMbeLBIDU/hAaYAoWJTReH",
	"22Rs0Q2utcOhm3xnFB3L2PoLHin6yOSO1HSkpjugptZDsNt/BF3e+5xFju1Qo2fI6BkyeoZ8MZ4hgTti",
	"s3yQRUKX5p7YcuWYBc6sZr2mclMNcVEz8nezEwBVSoA1cV7eCBaAZCWhHGC+HcwLBrFxDgBwyJP0AG9T",
	"5d4/KGFUj3e4Met4YAc2Qz2A9D0yb0V9r23olhVZT+5Ur4/0dfSZ+dp9ZhCfhjjI1N7tNm+YoozBXQgD",
	"dvB79nPxZx01J6NTy6dAzyaXPcBd5di5q/TiLrYscHcrZUNt8NH7ZJSmPydjtvcCtoeA9WPQC6Z3hj47",
	"cxe5Dx5yxJ0Rd/q9PnrxBxruDING540dYvHI2I5K7C+Jl25xy0Bb3BBaZR0wdkatPgvXim1k7/ujTqOc",
	"P5LDkRzejWphP2ZQykIVyWRCZLPIzlOq51EF4PVtqhvKjztUOpSDfha01IfCyPWNZO5rEhjbiY5kImaA",
	"Ax05edDWhw29tHcNlcyZbbNL1UxocmdQLcvw7ooCTVsrAV2J9EYUC/nZJa0LGx2h8Vm17eSPqjh6iuhR",
	"v82Q+MlMPpKKkSP6NMSpzK3cSZr8tJLDNcfnLsX6qD8e9cej/tjTH2+NU542eWdYNeqUR+liJCefCznp",
	"0PBuTU0q+t6d0ZNR6zvSj5F+jCJHXeRgQqZJsmZCD0hOXDauODWHhIxnRdMiP/FgEkYHBglj2AXkaReE",
	"K5VXE7NANa9Mptc8ZvHUTzNuHbZXLLoivC+Izfp1q/Ak4L8NvvJckYgqVriUc6e7sf74dYhACQ+aJLb2",
	"oOk7tVVBCij7E6FbPqx8zrAuWWu8h5KfTN3SOPiRro582X1SuRJ9gmFjjc89EWTlfR6YebjRYYwrG+PK",
	"xriyMePwls/nmGl4jJpqfdD6AqhEx7vVFkzV6HFHcVXNee45xKplAaMX1hht9UfmU7eIwdoO/bFXCP23",
	"0jq2TzlGaY0i5OcuQnYFbG2HbhXt2J3g2mdikh/0Do849zXjXHeg13Z4B53uGPNGs/3dYP/IgI8WuC+U",
	"5+8JENuOxlnngTumcp+FM8Et1QyfhMCN2o2RuI7E9RMpVG6RdTdAlAOFgbHXHdDizy6vbmMLRa7hT02T",
	"3UL6lT4jlRyl3j8Ozdo+NuTjlVS3c0YdVVUj0n71qqqPwsWw4uousHFUX43qq5EMjRLWztRXH0X32pRZ",
	"d0H5RpXWyAaNbNBOZZdrM0+rhHLGtOTsmilCC0da7DK7FGHHahywz5n6q/HXPU+lJqmMmYQYGFuRAPxn",
	"zYb4milN11nVV/qBGeMBeSjYjSGBCy6Vbl0cDF5ZVIxDQXVyFU2mEybytbkMFP6CH99Nb+trjOeP52aO",
	"yDkL9/mh76Y4xBfthX+nwrE5ttFP+av3UzbXoPoGLBLG+gJsnps2fUE1z3GgMZBmDKQZA2m+3AJNJzZ2",
	"tq0Sk9s00JW2ldDYZmBT5zjIpyt8BGRrfBm/9pcRruuQskfVt7AtUAda3VFwDo59zwE53qSjm8oYhPMJ",
	"MLPBs+7/Dv/9sK/ZOkuoNqyR4qloZ2bhIXatSdE8xM1e2FY/l416VZlQLtA9h41pWhSXC49S3DID6MhT",
	"jzz1yFOPwemGztbo1sjYjoztts/ngCDW2BUSrL9yLYGrtVv50Y/p3b2ldZPkwJnH6NjR7hf/EaXZIB8s",
	"GY2RCSxewF5EfsH0iMX3icV1aI/o/NWjc+ANH17zt09xhQ2d4morv53q0GMqiRG7vqDHEuv99mHPC6Z3",
	"hDo7dLf/Oow3I+6OuNtbb7gPf6HdjjB4dNHfHQKPCqrRLf8LMmL1lRruI1PW335HhOqz8Kjfwtx9b3Rp",
	"tKyPdHCkg3egyegLmgbNZRmtVNVhOqoYlsxuF5J0p/LZKBqNotGnFo3qxa+GC0q7QqhRXBrFpZGSfB6U",
	"JA++ySCTbPks+5LMrijJKM+M3MCIw0MZb3SFHBT9G3OluYh04bKIfYug1hLZS3TcZKwtTPglzjwA380o",
	"1ouwwHJpF1YsQqbr1jL3XMSdSO+CY22FySGBsYdkwRPrYVtfSyqSDfrYFtFyRK+o70e75NdMYPvCNfRO",
	"/E53sEp0uexb5c59Rsvrhuu9l2jj2wlj7D1dZwn2wNU+w18Aqa197GBifyw9Vg3mJA4NwDUV4/WvuUzF",
	"mgn9fSbTOI80OtpItuSp+D5Xe4wqvffEbIAz+f2cRldMxIjYw2gIIN/oF/q1+4XC5as+CKlcUsF/g3Vs",
	"lxWi0nNGyBtDYBBlVfUj0hmDw7likqyoIjSKmDJIHo4rflNZ1R3ySP5EI358rfhR0mwIfU9rt8+hj/97",
	"FYsky1LFdSo56wmrP3MtN32x9Wf+mGOE/RgNNEYDjdFAA8hfSWHGB+1rZ/iKd2kzJMw98Da1xbqXTe8o",
	"4N2b4J6j3uszjwb6MfT9U6FsC4u5TQjAIKTG1hWk3kotH5hkjAgYleWfk7K89lR2hAUMwqgXTO8cnT4T",
	"L5TuB3TEp68Sn3pc9QfhlPXC2DFWja4oO8bskSse3Va/NEa8z4d/EP2y7i87p2CfhQvMtgL9/VKtUYEw",
	"ksqRVO5eZ2EtXBsR9drFsOn5RkT9lrGy7WgaG01jo2lsNI0NfJlLwjEax0bjWPk6DTOPBZ6odgNZ2fjO",
	"TGTeFPduJKvPPXK5o5ns0yFvG9O5naVsEH47W1kFv7cU4wMTjfayUcr8vPT7tdez02I2CLPAZnYHaPXZ",
	"2M2639QRs75SzOq1nQ3CLms4ugP8Gi1oO8fxkWUeFcNfHpfeb0UbRMkKO9od0LLPxJa2reR/3xRs1DWM",
	"hHMknLtXb9i88G2mNCNuKTu0l/a+IWaV2fzvjE4MSGH/leqd3SG+g75o18E3K5fJ5GCyPzHvhm1dP+E3",
	"7igxEYOhCUxou4WZl7C58mHSNEh5A6WCHDGp+cK0Zud8KbhYWgJXtcU602TZWmFrWZDD7nkw5UJwUExH",
	"3TvCs6K8fdcKm0XwO8c1oLQJE7hYuoL33nBQQ7lvaYGSyZXyFtsswWZBoJFMlSIxXyyYZCI8OoZ1bzO6",
	"H/YcHLIS6tq377aYVjuW5x3QP1KbF0AxlkcXB+w4Yhw2HCCKdkSHjR/effj/AwAA//83Wc77qTECAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
